package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name = "administrador", catalog = "pueblosMagicos")
public class Administrador implements java.io.Serializable {

	private int UIdUsuario;

	public Administrador() {
	}

	public Administrador(int UIdUsuario) {
		this.UIdUsuario = UIdUsuario;
	}

	@Id

	@Column(name = "u_idUsuario", unique = true, nullable = false)
	public int getUIdUsuario() {
		return this.UIdUsuario;
	}

	public void setUIdUsuario(int UIdUsuario) {
		this.UIdUsuario = UIdUsuario;
	}

}
