package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name = "administrador", catalog = "pueblosMagicos")
public class Administrador implements java.io.Serializable
{

	private Integer UIdUsuario;

	public Administrador()
	{
	}

	public Administrador(Integer UIdUsuario)
	{
		this.UIdUsuario = UIdUsuario;
	}

	@Id

	@Column(name = "u_idUsuario", unique = true, nullable = false)
	public Integer getUIdUsuario( )
	{
		return this.UIdUsuario;
	}

	public void setUIdUsuario( Integer UIdUsuario )
	{
		this.UIdUsuario = UIdUsuario;
	}

}
