package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Asentamiento generated by hbm2java
 */
@Entity
@Table(name = "asentamiento", catalog = "pueblosMagicos")
public class Asentamiento implements java.io.Serializable
{

	private Integer idAsentaminto;
	private String nombreAsentamiento;
	private int taIdtipoAsentamiento;
	private int mIdMunicipio;

	public Asentamiento()
	{
	}

	public Asentamiento(int idAsentaminto, String nombreAsentamiento, int taIdtipoAsentamiento, int mIdMunicipio)
	{
		this.idAsentaminto = idAsentaminto;
		this.nombreAsentamiento = nombreAsentamiento;
		this.taIdtipoAsentamiento = taIdtipoAsentamiento;
		this.mIdMunicipio = mIdMunicipio;
	}

	

	@AttributeOverrides({
			@AttributeOverride(name = "idAsentamiento", column = @Column(name = "idAsentamiento", nullable = false)),
			@AttributeOverride(name = "mIdMunicipio", column = @Column(name = "m_idMunicipio", nullable = false)),
			@AttributeOverride(name = "taIdtipoAsentamiento", column = @Column(name = "ta_idtipoAsentamiento", nullable = false))})
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	public Integer getIdAsentaminto( )
	{
		return this.idAsentaminto;
	}

	public void setIdAsentaminto( Integer idAsentaminto )
	{
		this.idAsentaminto = idAsentaminto;
	}
	
	

	@Column(name = "nombreAsentamiento", length = 60)
	public String getNombreAsentamiento( )
	{
		return this.nombreAsentamiento;
	}

	public void setNombreAsentamiento( String nombreAsentamiento )
	{
		this.nombreAsentamiento = nombreAsentamiento;
	}

	@Column(name = "tA_idtipoAsentamiento", nullable = false)
	public int getTaIdtipoAsentamiento( )
	{
		return this.taIdtipoAsentamiento;
	}

	public void setTaIdtipoAsentamiento( int taIdtipoAsentamiento )
	{
		this.taIdtipoAsentamiento = taIdtipoAsentamiento;
	}
	
	@Column(name = "m_idMunicipio", nullable = false)
	public int getMIdMunicipio( )
	{
		return this.mIdMunicipio;
	}

	public void setMIdMunicipio( int mIdMunicipio )
	{
		this.mIdMunicipio = mIdMunicipio;
	}

}
