package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Asentamiento generated by hbm2java
 */
@Entity
@Table(name = "asentamiento", catalog = "pueblosMagicos")
public class Asentamiento implements java.io.Serializable {

	private AsentamientoId id;
	private String nombreAsentamiento;
	private int taIdtipoAsentamiento;

	public Asentamiento() {
	}

	public Asentamiento(AsentamientoId id, int taIdtipoAsentamiento) {
		this.id = id;
		this.taIdtipoAsentamiento = taIdtipoAsentamiento;
	}

	public Asentamiento(AsentamientoId id, String nombreAsentamiento, int taIdtipoAsentamiento) {
		this.id = id;
		this.nombreAsentamiento = nombreAsentamiento;
		this.taIdtipoAsentamiento = taIdtipoAsentamiento;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAsentamiento", column = @Column(name = "idAsentamiento", nullable = false)),
			@AttributeOverride(name = "MEIdEstado", column = @Column(name = "m_e_idEstado", nullable = false)),
			@AttributeOverride(name = "MIdMunicipio", column = @Column(name = "m_idMunicipio", nullable = false)) })
	public AsentamientoId getId() {
		return this.id;
	}

	public void setId(AsentamientoId id) {
		this.id = id;
	}

	@Column(name = "nombreAsentamiento", length = 60)
	public String getNombreAsentamiento() {
		return this.nombreAsentamiento;
	}

	public void setNombreAsentamiento(String nombreAsentamiento) {
		this.nombreAsentamiento = nombreAsentamiento;
	}

	@Column(name = "tA_idtipoAsentamiento", nullable = false)
	public int getTaIdtipoAsentamiento() {
		return this.taIdtipoAsentamiento;
	}

	public void setTaIdtipoAsentamiento(int taIdtipoAsentamiento) {
		this.taIdtipoAsentamiento = taIdtipoAsentamiento;
	}

}
