package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AsentamientoId generated by hbm2java
 */
@Embeddable
public class AsentamientoId implements java.io.Serializable
{

	private Integer idAsentamiento;
	private Integer MEIdEstado;
	private Integer MIdMunicipio;

	public AsentamientoId()
	{
	}

	public AsentamientoId(Integer idAsentamiento, Integer MEIdEstado, Integer MIdMunicipio)
	{
		this.idAsentamiento = idAsentamiento;
		this.MEIdEstado = MEIdEstado;
		this.MIdMunicipio = MIdMunicipio;
	}

	@Column(name = "idAsentamiento", nullable = false)
	public Integer getIdAsentamiento( )
	{
		return this.idAsentamiento;
	}

	public void setIdAsentamiento( Integer idAsentamiento )
	{
		this.idAsentamiento = idAsentamiento;
	}

	@Column(name = "m_e_idEstado", nullable = false)
	public Integer getMEIdEstado( )
	{
		return this.MEIdEstado;
	}

	public void setMEIdEstado( Integer MEIdEstado )
	{
		this.MEIdEstado = MEIdEstado;
	}

	@Column(name = "m_idMunicipio", nullable = false)
	public Integer getMIdMunicipio( )
	{
		return this.MIdMunicipio;
	}

	public void setMIdMunicipio( Integer MIdMunicipio )
	{
		this.MIdMunicipio = MIdMunicipio;
	}

	public boolean equals( Object other )
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AsentamientoId))
			return false;
		AsentamientoId castOther = (AsentamientoId) other;

		return (this.getIdAsentamiento() == castOther.getIdAsentamiento())
				&& (this.getMEIdEstado() == castOther.getMEIdEstado())
				&& (this.getMIdMunicipio() == castOther.getMIdMunicipio());
	}

	public int hashCode( )
	{
		int result = 17;

		result = 37 * result + this.getIdAsentamiento();
		result = 37 * result + this.getMEIdEstado();
		result = 37 * result + this.getMIdMunicipio();
		return result;
	}

}
