package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Asentamiento generated by hbm2java
 */
@Entity
@Table(name = "asentamiento", catalog = "pueblosMagicos")
public class Asentamiento implements java.io.Serializable
{

	private Integer idAsentamiento;
	private String nombreAsentamiento;
	private Integer taIdtipoAsentamiento;
	private Integer MIdMunicipio;

	public Asentamiento()
	{
	}

	public Asentamiento(Integer idAsentamiento, String nombreAsentamiento, Integer taIdtipoAsentamiento, Integer mIdMunicipio)
	{
		this.idAsentamiento = idAsentamiento;
		this.nombreAsentamiento = nombreAsentamiento;
		this.taIdtipoAsentamiento = taIdtipoAsentamiento;
		this.MIdMunicipio = mIdMunicipio;
	}

	

	@AttributeOverrides({
			@AttributeOverride(name = "idAsentamiento", column = @Column(name = "idAsentamiento", nullable = false)),
			@AttributeOverride(name = "nombreAsentamiento", column = @Column(name = "nombreAsentamiento")),
			@AttributeOverride(name = "MIdMunicipio", column = @Column(name = "m_idMunicipio", nullable = false)),
			@AttributeOverride(name = "taIdtipoAsentamiento", column = @Column(name = "ta_idtipoAsentamiento", nullable = false))})
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	public Integer getIdAsentamiento( )
	{
		return this.idAsentamiento;
	}

	public void setIdAsentamiento( Integer idAsentamiento )
	{
		this.idAsentamiento = idAsentamiento;
	}
	
	

	@Column(name = "nombreAsentamiento", length = 60)
	public String getNombreAsentamiento( )
	{
		return this.nombreAsentamiento;
	}

	public void setNombreAsentamiento( String nombreAsentamiento )
	{
		this.nombreAsentamiento = nombreAsentamiento;
	}

	@Column(name = "tA_idtipoAsentamiento", nullable = false)
	public Integer getTaIdtipoAsentamiento( )
	{
		return this.taIdtipoAsentamiento;
	}

	public void setTaIdtipoAsentamiento( Integer taIdtipoAsentamiento )
	{
		this.taIdtipoAsentamiento = taIdtipoAsentamiento;
	}
	
	@Column(name = "m_idMunicipio", nullable = false)
	public Integer getMIdMunicipio( )
	{
		return this.MIdMunicipio;
	}

	public void setMIdMunicipio( Integer MIdMunicipio )
	{
		this.MIdMunicipio = MIdMunicipio;
	}

}
