package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Asociacion generated by hbm2java
 */
@Entity
@Table(name = "asociacion", catalog = "pueblosMagicos")
public class Asociacion implements java.io.Serializable
{

	private Integer idasociacion;
	private String nombre;

	public Asociacion()
	{
	}

	public Asociacion(String nombre)
	{
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idasociacion", unique = true, nullable = false)
	public Integer getIdasociacion( )
	{
		return this.idasociacion;
	}

	public void setIdasociacion( Integer idasociacion )
	{
		this.idasociacion = idasociacion;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre( )
	{
		return this.nombre;
	}

	public void setNombre( String nombre )
	{
		this.nombre = nombre;
	}

}
