package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Atractivoturistico generated by hbm2java
 */
@Entity
@Table(name = "atractivoturistico", catalog = "pueblosMagicos")
public class Atractivoturistico implements java.io.Serializable {

	private Integer idAtractivoTuristico;
	private String nombre;
	private String descripcion;
	private double latitud;
	private double longitud;
	private Date fechaInicio;
	private Date fechaFin;
	private String estadoRegistro;
	private Integer TIdUsuario;
	private Date horaInicio;
	private Date horaFin;
	private int taIdtipoAtractivo;
	private Integer AIdUsuario;
	private int AIdAsentamiento;

	public Atractivoturistico() {
	}

	public Atractivoturistico(double latitud, double longitud, int taIdtipoAtractivo, int AIdAsentamiento) {
		this.latitud = latitud;
		this.longitud = longitud;
		this.taIdtipoAtractivo = taIdtipoAtractivo;
		this.AIdAsentamiento = AIdAsentamiento;
	}

	public Atractivoturistico(String nombre, String descripcion, double latitud, double longitud, Date fechaInicio,
			Date fechaFin, String estadoRegistro, Integer TIdUsuario, Date horaInicio, Date horaFin,
			int taIdtipoAtractivo, Integer AIdUsuario, int AIdAsentamiento) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.latitud = latitud;
		this.longitud = longitud;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estadoRegistro = estadoRegistro;
		this.TIdUsuario = TIdUsuario;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.taIdtipoAtractivo = taIdtipoAtractivo;
		this.AIdUsuario = AIdUsuario;
		this.AIdAsentamiento = AIdAsentamiento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAtractivoTuristico", unique = true, nullable = false)
	public Integer getIdAtractivoTuristico() {
		return this.idAtractivoTuristico;
	}

	public void setIdAtractivoTuristico(Integer idAtractivoTuristico) {
		this.idAtractivoTuristico = idAtractivoTuristico;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "latitud", nullable = false, precision = 22, scale = 0)
	public double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", nullable = false, precision = 22, scale = 0)
	public double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(double longitud) {
		this.longitud = longitud;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaInicio", length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaFin", length = 10)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "estadoRegistro", length = 45)
	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	@Column(name = "t_idUsuario")
	public Integer getTIdUsuario() {
		return this.TIdUsuario;
	}

	public void setTIdUsuario(Integer TIdUsuario) {
		this.TIdUsuario = TIdUsuario;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horaInicio", length = 8)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horaFin", length = 8)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	@Column(name = "tA_idtipoAtractivo", nullable = false)
	public int getTaIdtipoAtractivo() {
		return this.taIdtipoAtractivo;
	}

	public void setTaIdtipoAtractivo(int taIdtipoAtractivo) {
		this.taIdtipoAtractivo = taIdtipoAtractivo;
	}

	@Column(name = "a_idUsuario")
	public Integer getAIdUsuario() {
		return this.AIdUsuario;
	}

	public void setAIdUsuario(Integer AIdUsuario) {
		this.AIdUsuario = AIdUsuario;
	}

	@Column(name = "a_idAsentamiento", nullable = false)
	public int getAIdAsentamiento() {
		return this.AIdAsentamiento;
	}

	public void setAIdAsentamiento(int AIdAsentamiento) {
		this.AIdAsentamiento = AIdAsentamiento;
	}

}
