package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Calificacionatractivoturistico generated by hbm2java
 */
@Entity
@Table(name = "calificacionatractivoturistico", catalog = "pueblosMagicos")
public class Calificacionatractivoturistico implements java.io.Serializable
{

	private Integer idCalificacionAtractivoTuristico;
	private Integer calificacion;
	private String comentario;
	private Integer atIdatractivoTuristico;
	private Integer TIdusuario;

	public Calificacionatractivoturistico()
	{
	}

	public Calificacionatractivoturistico(Integer atIdatractivoTuristico, Integer TIdusuario)
	{
		this.atIdatractivoTuristico = atIdatractivoTuristico;
		this.TIdusuario = TIdusuario;
	}

	public Calificacionatractivoturistico(Integer calificacion, String comentario, Integer atIdatractivoTuristico,
			Integer TIdusuario)
	{
		this.calificacion = calificacion;
		this.comentario = comentario;
		this.atIdatractivoTuristico = atIdatractivoTuristico;
		this.TIdusuario = TIdusuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCalificacionAtractivoTuristico", unique = true, nullable = false)
	public Integer getIdCalificacionAtractivoTuristico( )
	{
		return this.idCalificacionAtractivoTuristico;
	}

	public void setIdCalificacionAtractivoTuristico( Integer idCalificacionAtractivoTuristico )
	{
		this.idCalificacionAtractivoTuristico = idCalificacionAtractivoTuristico;
	}

	@Column(name = "calificacion")
	public Integer getCalificacion( )
	{
		return this.calificacion;
	}

	public void setCalificacion( Integer calificacion )
	{
		this.calificacion = calificacion;
	}

	@Column(name = "comentario", length = 65535)
	public String getComentario( )
	{
		return this.comentario;
	}

	public void setComentario( String comentario )
	{
		this.comentario = comentario;
	}

	@Column(name = "aT_idatractivoTuristico", nullable = false)
	public Integer getAtIdatractivoTuristico( )
	{
		return this.atIdatractivoTuristico;
	}

	public void setAtIdatractivoTuristico( Integer atIdatractivoTuristico )
	{
		this.atIdatractivoTuristico = atIdatractivoTuristico;
	}

	@Column(name = "t_idusuario", nullable = false)
	public Integer getTIdusuario( )
	{
		return this.TIdusuario;
	}

	public void setTIdusuario( Integer TIdusuario )
	{
		this.TIdusuario = TIdusuario;
	}

}
