package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Calificacionatractivoturistico generated by hbm2java
 */
@Entity
@Table(name = "calificacionatractivoturistico", catalog = "pueblosMagicos")
public class Calificacionatractivoturistico implements java.io.Serializable {

	private Integer idCalificacionAtractivoTuristico;
	private int calificacion;
	private String comentario;
	private int atIdatractivoTuristico;
	private int TIdusuario;

	public Calificacionatractivoturistico() {
	}

	public Calificacionatractivoturistico(int calificacion, int atIdatractivoTuristico, int TIdusuario) {
		this.calificacion = calificacion;
		this.atIdatractivoTuristico = atIdatractivoTuristico;
		this.TIdusuario = TIdusuario;
	}

	public Calificacionatractivoturistico(int calificacion, String comentario, int atIdatractivoTuristico,
			int TIdusuario) {
		this.calificacion = calificacion;
		this.comentario = comentario;
		this.atIdatractivoTuristico = atIdatractivoTuristico;
		this.TIdusuario = TIdusuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCalificacionAtractivoTuristico", unique = true, nullable = false)
	public Integer getIdCalificacionAtractivoTuristico() {
		return this.idCalificacionAtractivoTuristico;
	}

	public void setIdCalificacionAtractivoTuristico(Integer idCalificacionAtractivoTuristico) {
		this.idCalificacionAtractivoTuristico = idCalificacionAtractivoTuristico;
	}

	@Column(name = "calificacion", nullable = false)
	public int getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(int calificacion) {
		this.calificacion = calificacion;
	}

	@Column(name = "comentario", length = 65535)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "aT_idatractivoTuristico", nullable = false)
	public int getAtIdatractivoTuristico() {
		return this.atIdatractivoTuristico;
	}

	public void setAtIdatractivoTuristico(int atIdatractivoTuristico) {
		this.atIdatractivoTuristico = atIdatractivoTuristico;
	}

	@Column(name = "t_idusuario", nullable = false)
	public int getTIdusuario() {
		return this.TIdusuario;
	}

	public void setTIdusuario(int TIdusuario) {
		this.TIdusuario = TIdusuario;
	}

}
