package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Calificacionpueblomagico generated by hbm2java
 */
@Entity
@Table(name = "calificacionpueblomagico", catalog = "pueblosMagicos")
public class Calificacionpueblomagico implements java.io.Serializable
{

	private Integer idCalificación;
	private Integer calificación;
	private String comentario;
	private int TIdUsuario;
	private int pmIdPuebloMagico;

	public Calificacionpueblomagico()
	{
	}

	public Calificacionpueblomagico(int TIdUsuario, int pmIdPuebloMagico)
	{
		this.TIdUsuario = TIdUsuario;
		this.pmIdPuebloMagico = pmIdPuebloMagico;
	}

	public Calificacionpueblomagico(Integer calificación, String comentario, int TIdUsuario, int pmIdPuebloMagico)
	{
		this.calificación = calificación;
		this.comentario = comentario;
		this.TIdUsuario = TIdUsuario;
		this.pmIdPuebloMagico = pmIdPuebloMagico;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCalificación", unique = true, nullable = false)
	public Integer getIdCalificación( )
	{
		return this.idCalificación;
	}

	public void setIdCalificación( Integer idCalificación )
	{
		this.idCalificación = idCalificación;
	}

	@Column(name = "calificación")
	public Integer getCalificación( )
	{
		return this.calificación;
	}

	public void setCalificación( Integer calificación )
	{
		this.calificación = calificación;
	}

	@Column(name = "comentario", length = 65535)
	public String getComentario( )
	{
		return this.comentario;
	}

	public void setComentario( String comentario )
	{
		this.comentario = comentario;
	}

	@Column(name = "t_idUsuario", nullable = false)
	public int getTIdUsuario( )
	{
		return this.TIdUsuario;
	}

	public void setTIdUsuario( int TIdUsuario )
	{
		this.TIdUsuario = TIdUsuario;
	}

	@Column(name = "pM_idPuebloMagico", nullable = false)
	public int getPmIdPuebloMagico( )
	{
		return this.pmIdPuebloMagico;
	}

	public void setPmIdPuebloMagico( int pmIdPuebloMagico )
	{
		this.pmIdPuebloMagico = pmIdPuebloMagico;
	}

}
