package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Establecimiento generated by hbm2java
 */
@Entity
@Table(name = "establecimiento", catalog = "pueblosMagicos")
public class Establecimiento implements java.io.Serializable
{

	private Integer idEstablecimiento;
	private Integer pstIdUsuario;
	private String nombreComercial;
	private String rfc;
	private String nombreVialidad;
	private String numeroExterior;
	private String numeroInterior;
	private Integer VIdUsuario;
	private Integer tvIdTipoVialidad;
	private Double longitud;
	private Double latitud;
	private Integer AIdAsentamiento;
	private Integer erIdEstadoRegistro;

	public Establecimiento()
	{
	}

	public Establecimiento(Integer pstIdUsuario, Integer tvIdTipoVialidad, Integer AIdAsentamiento,
			Integer erIdEstadoRegistro)
	{
		this.pstIdUsuario = pstIdUsuario;
		this.tvIdTipoVialidad = tvIdTipoVialidad;
		this.AIdAsentamiento = AIdAsentamiento;
		this.erIdEstadoRegistro = erIdEstadoRegistro;
	}

	public Establecimiento(Integer pstIdUsuario, String nombreComercial, String rfc, String nombreVialidad,
			String numeroExterior, String numeroInterior, Integer VIdUsuario,
			Integer tvIdTipoVialidad, Double longitud, Double latitud, Integer AIdAsentamiento, Integer erIdEstadoRegistro)
	{
		this.pstIdUsuario = pstIdUsuario;
		this.nombreComercial = nombreComercial;
		this.rfc = rfc;
		this.nombreVialidad = nombreVialidad;
		this.numeroExterior = numeroExterior;
		this.numeroInterior = numeroInterior;
		this.VIdUsuario = VIdUsuario;
		this.tvIdTipoVialidad = tvIdTipoVialidad;
		this.longitud = longitud;
		this.latitud = latitud;
		this.AIdAsentamiento = AIdAsentamiento;
		this.erIdEstadoRegistro = erIdEstadoRegistro;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEstablecimiento", unique = true, nullable = false)
	public Integer getIdEstablecimiento( )
	{
		return this.idEstablecimiento;
	}

	public void setIdEstablecimiento( Integer idEstablecimiento )
	{
		this.idEstablecimiento = idEstablecimiento;
	}

	@Column(name = "PST_idUsuario", nullable = false)
	public Integer getPstIdUsuario( )
	{
		return this.pstIdUsuario;
	}

	public void setPstIdUsuario( Integer pstIdUsuario )
	{
		this.pstIdUsuario = pstIdUsuario;
	}

	@Column(name = "nombreComercial", length = 80)
	public String getNombreComercial( )
	{
		return this.nombreComercial;
	}

	public void setNombreComercial( String nombreComercial )
	{
		this.nombreComercial = nombreComercial;
	}

	@Column(name = "RFC", length = 15)
	public String getRfc( )
	{
		return this.rfc;
	}

	public void setRfc( String rfc )
	{
		this.rfc = rfc;
	}

	@Column(name = "nombreVialidad", length = 80)
	public String getNombreVialidad( )
	{
		return this.nombreVialidad;
	}

	public void setNombreVialidad( String nombreVialidad )
	{
		this.nombreVialidad = nombreVialidad;
	}

	@Column(name = "numeroExterior", length = 5)
	public String getNumeroExterior( )
	{
		return this.numeroExterior;
	}

	public void setNumeroExterior( String numeroExterior )
	{
		this.numeroExterior = numeroExterior;
	}

	@Column(name = "numeroInterior", length = 5)
	public String getNumeroInterior( )
	{
		return this.numeroInterior;
	}

	public void setNumeroInterior( String numeroInterior )
	{
		this.numeroInterior = numeroInterior;
	}

	@Column(name = "v_idUsuario")
	public Integer getVIdUsuario( )
	{
		return this.VIdUsuario;
	}

	public void setVIdUsuario( Integer VIdUsuario )
	{
		this.VIdUsuario = VIdUsuario;
	}

	@Column(name = "tV_idTipoVialidad", nullable = false)
	public Integer getTvIdTipoVialidad( )
	{
		return this.tvIdTipoVialidad;
	}

	public void setTvIdTipoVialidad( Integer tvIdTipoVialidad )
	{
		this.tvIdTipoVialidad = tvIdTipoVialidad;
	}

	@Column(name = "longitud", precision = 22, scale = 0)
	public Double getLongitud( )
	{
		return this.longitud;
	}

	public void setLongitud( Double longitud )
	{
		this.longitud = longitud;
	}

	@Column(name = "latitud", precision = 22, scale = 0)
	public Double getLatitud( )
	{
		return this.latitud;
	}

	public void setLatitud( Double latitud )
	{
		this.latitud = latitud;
	}

	@Column(name = "a_idAsentamiento", nullable = false)
	public Integer getAIdAsentamiento( )
	{
		return this.AIdAsentamiento;
	}

	public void setAIdAsentamiento( Integer AIdAsentamiento )
	{
		this.AIdAsentamiento = AIdAsentamiento;
	}

	@Column(name = "eR_idEstadoRegistro", nullable = false)
	public Integer getErIdEstadoRegistro( )
	{
		return this.erIdEstadoRegistro;
	}

	public void setErIdEstadoRegistro( Integer erIdEstadoRegistro )
	{
		this.erIdEstadoRegistro = erIdEstadoRegistro;
	}

}
