package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Estadopueblomagico generated by hbm2java
 */
@Entity
@Table(name = "estadopueblomagico", catalog = "pueblosMagicos")
public class Estadopueblomagico implements java.io.Serializable
{

	private Integer idestadoPuebloMagico;
	private String estado;

	public Estadopueblomagico()
	{
	}

	public Estadopueblomagico(Integer idestadoPuebloMagico)
	{
		this.idestadoPuebloMagico = idestadoPuebloMagico;
	}

	public Estadopueblomagico(Integer idestadoPuebloMagico, String estado)
	{
		this.idestadoPuebloMagico = idestadoPuebloMagico;
		this.estado = estado;
	}

	@Id

	@Column(name = "idestadoPuebloMagico", unique = true, nullable = false)
	public Integer getIdestadoPuebloMagico( )
	{
		return this.idestadoPuebloMagico;
	}

	public void setIdestadoPuebloMagico( Integer idestadoPuebloMagico )
	{
		this.idestadoPuebloMagico = idestadoPuebloMagico;
	}

	@Column(name = "estado", length = 45)
	public String getEstado( )
	{
		return this.estado;
	}

	public void setEstado( String estado )
	{
		this.estado = estado;
	}

}
