package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Estadoregistro generated by hbm2java
 */
@Entity
@Table(name = "estadoregistro", catalog = "pueblosMagicos")
public class Estadoregistro implements java.io.Serializable
{

	private Integer idEstadoRegistro;
	private String estado;

	public Estadoregistro()
	{
	}

	public Estadoregistro(String estado)
	{
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEstadoRegistro", unique = true, nullable = false)
	public Integer getIdEstadoRegistro( )
	{
		return this.idEstadoRegistro;
	}

	public void setIdEstadoRegistro( Integer idEstadoRegistro )
	{
		this.idEstadoRegistro = idEstadoRegistro;
	}

	@Column(name = "estado", length = 45)
	public String getEstado( )
	{
		return this.estado;
	}

	public void setEstado( String estado )
	{
		this.estado = estado;
	}

}
