package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Establecimiento generated by hbm2java
 */
@Entity
@Table(name = "establecimiento", catalog = "pueblosMagicos")
public class Establecimiento implements java.io.Serializable {

	private Integer idEstablecimiento;
	private int pstIdUsuario;
	private String nombreComercial;
	private String rfc;
	private String nombreVialidad;
	private String numeroExterior;
	private String numeroInterior;
	private String telefono;
	private String extensionTelefono;
	private int VIdUsuario;
	private int tvIdTipoVialidad;
	private double longitud;
	private double lalitud;
	private int ereIdestadoRegistroEstablecimiento;
	private int AIdAsentamiento;

	public Establecimiento() {
	}

	public Establecimiento(int pstIdUsuario, int VIdUsuario, int tvIdTipoVialidad, double longitud, double lalitud,
			int ereIdestadoRegistroEstablecimiento, int AIdAsentamiento) {
		this.pstIdUsuario = pstIdUsuario;
		this.VIdUsuario = VIdUsuario;
		this.tvIdTipoVialidad = tvIdTipoVialidad;
		this.longitud = longitud;
		this.lalitud = lalitud;
		this.ereIdestadoRegistroEstablecimiento = ereIdestadoRegistroEstablecimiento;
		this.AIdAsentamiento = AIdAsentamiento;
	}

	public Establecimiento(int pstIdUsuario, String nombreComercial, String rfc, String nombreVialidad,
			String numeroExterior, String numeroInterior, String telefono, String extensionTelefono, int VIdUsuario,
			int tvIdTipoVialidad, double longitud, double lalitud, int ereIdestadoRegistroEstablecimiento,
			int AIdAsentamiento) {
		this.pstIdUsuario = pstIdUsuario;
		this.nombreComercial = nombreComercial;
		this.rfc = rfc;
		this.nombreVialidad = nombreVialidad;
		this.numeroExterior = numeroExterior;
		this.numeroInterior = numeroInterior;
		this.telefono = telefono;
		this.extensionTelefono = extensionTelefono;
		this.VIdUsuario = VIdUsuario;
		this.tvIdTipoVialidad = tvIdTipoVialidad;
		this.longitud = longitud;
		this.lalitud = lalitud;
		this.ereIdestadoRegistroEstablecimiento = ereIdestadoRegistroEstablecimiento;
		this.AIdAsentamiento = AIdAsentamiento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEstablecimiento", unique = true, nullable = false)
	public Integer getIdEstablecimiento() {
		return this.idEstablecimiento;
	}

	public void setIdEstablecimiento(Integer idEstablecimiento) {
		this.idEstablecimiento = idEstablecimiento;
	}

	@Column(name = "PST_idUsuario", nullable = false)
	public int getPstIdUsuario() {
		return this.pstIdUsuario;
	}

	public void setPstIdUsuario(int pstIdUsuario) {
		this.pstIdUsuario = pstIdUsuario;
	}

	@Column(name = "nombreComercial", length = 80)
	public String getNombreComercial() {
		return this.nombreComercial;
	}

	public void setNombreComercial(String nombreComercial) {
		this.nombreComercial = nombreComercial;
	}

	@Column(name = "RFC", length = 15)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	@Column(name = "nombreVialidad", length = 80)
	public String getNombreVialidad() {
		return this.nombreVialidad;
	}

	public void setNombreVialidad(String nombreVialidad) {
		this.nombreVialidad = nombreVialidad;
	}

	@Column(name = "numeroExterior", length = 5)
	public String getNumeroExterior() {
		return this.numeroExterior;
	}

	public void setNumeroExterior(String numeroExterior) {
		this.numeroExterior = numeroExterior;
	}

	@Column(name = "numeroInterior", length = 5)
	public String getNumeroInterior() {
		return this.numeroInterior;
	}

	public void setNumeroInterior(String numeroInterior) {
		this.numeroInterior = numeroInterior;
	}

	@Column(name = "telefono", length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "extensionTelefono", length = 5)
	public String getExtensionTelefono() {
		return this.extensionTelefono;
	}

	public void setExtensionTelefono(String extensionTelefono) {
		this.extensionTelefono = extensionTelefono;
	}

	@Column(name = "v_idUsuario", nullable = false)
	public int getVIdUsuario() {
		return this.VIdUsuario;
	}

	public void setVIdUsuario(int VIdUsuario) {
		this.VIdUsuario = VIdUsuario;
	}

	@Column(name = "tV_idTipoVialidad", nullable = false)
	public int getTvIdTipoVialidad() {
		return this.tvIdTipoVialidad;
	}

	public void setTvIdTipoVialidad(int tvIdTipoVialidad) {
		this.tvIdTipoVialidad = tvIdTipoVialidad;
	}

	@Column(name = "longitud", nullable = false, precision = 22, scale = 0)
	public double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(double longitud) {
		this.longitud = longitud;
	}

	@Column(name = "lalitud", nullable = false, precision = 22, scale = 0)
	public double getLalitud() {
		return this.lalitud;
	}

	public void setLalitud(double lalitud) {
		this.lalitud = lalitud;
	}

	@Column(name = "eRe_idestadoRegistroEstablecimiento", nullable = false)
	public int getEreIdestadoRegistroEstablecimiento() {
		return this.ereIdestadoRegistroEstablecimiento;
	}

	public void setEreIdestadoRegistroEstablecimiento(int ereIdestadoRegistroEstablecimiento) {
		this.ereIdestadoRegistroEstablecimiento = ereIdestadoRegistroEstablecimiento;
	}

	@Column(name = "a_idAsentamiento", nullable = false)
	public int getAIdAsentamiento() {
		return this.AIdAsentamiento;
	}

	public void setAIdAsentamiento(int AIdAsentamiento) {
		this.AIdAsentamiento = AIdAsentamiento;
	}

}
