package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Evaluacionservicioturistico generated by hbm2java
 */
@Entity
@Table(name = "evaluacionservicioturistico", catalog = "pueblosMagicos")
public class Evaluacionservicioturistico implements java.io.Serializable
{

	private Integer idEvaluacion;
	private String comentario;
	private int TIdUsuario;
	private int teIdEvaluacion;
	private Integer aspectoEstablecimiento;
	private Integer atencionCliente;
	private Integer eficienciaServicio;
	private Integer higieneEstablecimiento;
	private Integer relacionPrecioCalidad;
	private Integer accesibilidad;
	private Integer comunicacion;
	private Integer manejoIdiomas;
	private Integer senalamientoInterno;
	private Integer senalamientoExterno;
	private Integer sTIdServicioTuristico;

	public Evaluacionservicioturistico()
	{
	}

	public Evaluacionservicioturistico(int TIdUsuario, int teIdEvaluacion, int sTIdServicioTuristico)
	{
		this.TIdUsuario = TIdUsuario;
		this.teIdEvaluacion = teIdEvaluacion;
		this.sTIdServicioTuristico = sTIdServicioTuristico;
	}

	public Evaluacionservicioturistico(String comentario, int TIdUsuario, int teIdEvaluacion,
			Integer aspectoEstablecimiento, Integer atencionCliente, Integer eficienciaServicio,
			Integer higieneEstablecimiento, Integer relacionPrecioCalidad, Integer accesibilidad, Integer comunicacion,
			Integer manejoIdiomas, Integer senalamientoInterno, Integer senalamientoExterno , int sTIdServicioTuristico)
	{
		this.comentario = comentario;
		this.TIdUsuario = TIdUsuario;
		this.teIdEvaluacion = teIdEvaluacion;
		this.aspectoEstablecimiento = aspectoEstablecimiento;
		this.atencionCliente = atencionCliente;
		this.eficienciaServicio = eficienciaServicio;
		this.higieneEstablecimiento = higieneEstablecimiento;
		this.relacionPrecioCalidad = relacionPrecioCalidad;
		this.accesibilidad = accesibilidad;
		this.comunicacion = comunicacion;
		this.manejoIdiomas = manejoIdiomas;
		this.senalamientoInterno = senalamientoInterno;
		this.senalamientoExterno = senalamientoExterno;
		this.sTIdServicioTuristico = sTIdServicioTuristico;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEvaluacion", unique = true, nullable = false)
	public Integer getIdEvaluacion( )
	{
		return this.idEvaluacion;
	}

	public void setIdEvaluacion( Integer idEvaluacion )
	{
		this.idEvaluacion = idEvaluacion;
	}

	@Column(name = "comentario", length = 65535)
	public String getComentario( )
	{
		return this.comentario;
	}

	public void setComentario( String comentario )
	{
		this.comentario = comentario;
	}

	@Column(name = "t_idUsuario", nullable = false)
	public int getTIdUsuario( )
	{
		return this.TIdUsuario;
	}

	public void setTIdUsuario( int TIdUsuario )
	{
		this.TIdUsuario = TIdUsuario;
	}

	@Column(name = "tE_idEvaluacion", nullable = false)
	public int getTeIdEvaluacion( )
	{
		return this.teIdEvaluacion;
	}

	public void setTeIdEvaluacion( int teIdEvaluacion )
	{
		this.teIdEvaluacion = teIdEvaluacion;
	}

	@Column(name = "aspectoEstablecimiento")
	public Integer getAspectoEstablecimiento( )
	{
		return this.aspectoEstablecimiento;
	}

	public void setAspectoEstablecimiento( Integer aspectoEstablecimiento )
	{
		this.aspectoEstablecimiento = aspectoEstablecimiento;
	}

	@Column(name = "atencionCliente")
	public Integer getAtencionCliente( )
	{
		return this.atencionCliente;
	}

	public void setAtencionCliente( Integer atencionCliente )
	{
		this.atencionCliente = atencionCliente;
	}

	@Column(name = "eficienciaServicio")
	public Integer getEficienciaServicio( )
	{
		return this.eficienciaServicio;
	}

	public void setEficienciaServicio( Integer eficienciaServicio )
	{
		this.eficienciaServicio = eficienciaServicio;
	}

	@Column(name = "higieneEstablecimiento")
	public Integer getHigieneEstablecimiento( )
	{
		return this.higieneEstablecimiento;
	}

	public void setHigieneEstablecimiento( Integer higieneEstablecimiento )
	{
		this.higieneEstablecimiento = higieneEstablecimiento;
	}

	@Column(name = "relacionPrecioCalidad")
	public Integer getRelacionPrecioCalidad( )
	{
		return this.relacionPrecioCalidad;
	}

	public void setRelacionPrecioCalidad( Integer relacionPrecioCalidad )
	{
		this.relacionPrecioCalidad = relacionPrecioCalidad;
	}

	@Column(name = "accesibilidad")
	public Integer getAccesibilidad( )
	{
		return this.accesibilidad;
	}

	public void setAccesibilidad( Integer accesibilidad )
	{
		this.accesibilidad = accesibilidad;
	}

	@Column(name = "comunicacion")
	public Integer getComunicacion( )
	{
		return this.comunicacion;
	}

	public void setComunicacion( Integer comunicacion )
	{
		this.comunicacion = comunicacion;
	}

	@Column(name = "manejoIdiomas")
	public Integer getManejoIdiomas( )
	{
		return this.manejoIdiomas;
	}

	public void setManejoIdiomas( Integer manejoIdiomas )
	{
		this.manejoIdiomas = manejoIdiomas;
	}

	@Column(name = "senalamientoInterno")
	public Integer getSenalamientoInterno( )
	{
		return this.senalamientoInterno;
	}

	public void setSenalamientoInterno( Integer senalamientoInterno )
	{
		this.senalamientoInterno = senalamientoInterno;
	}

	@Column(name = "senalamientoExterno")
	public Integer getSenalamientoExterno( )
	{
		return this.senalamientoExterno;
	}

	public void setSenalamientoExterno( Integer senalamientoExterno )
	{
		this.senalamientoExterno = senalamientoExterno;
	}

	@Column(name = "sT_idServicioTuristico", nullable = false)
	public int getSTIdServicioTuristico( )
	{
		return this.sTIdServicioTuristico;
	}

	public void setSTIdServicioTuristico( int sTIdServicioTuristico )
	{
		this.sTIdServicioTuristico = sTIdServicioTuristico;
	}
}
