package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Evaluacionservicioturistico generated by hbm2java
 */
@Entity
@Table(name = "evaluacionservicioturistico", catalog = "pueblosMagicos")
public class Evaluacionservicioturistico implements java.io.Serializable {

	private Integer idEvaluacion;
	private String comentario;
	private int TIdUsuario;
	private int teIdEvaluacion;
	private int aspectoEstablecimiento;
	private int atencionCliente;
	private int eficienciaServicio;
	private int higieneEstablecimiento;
	private int relacionPrecioCalidad;
	private int accesibilidad;
	private int comunicacion;
	private int manejoIdiomas;
	private int senalamientoInterno;
	private int senalamientoExterno;

	public Evaluacionservicioturistico() {
	}

	public Evaluacionservicioturistico(int TIdUsuario, int teIdEvaluacion, int aspectoEstablecimiento,
			int atencionCliente, int eficienciaServicio, int higieneEstablecimiento, int relacionPrecioCalidad,
			int accesibilidad, int comunicacion, int manejoIdiomas, int senalamientoInterno, int senalamientoExterno) {
		this.TIdUsuario = TIdUsuario;
		this.teIdEvaluacion = teIdEvaluacion;
		this.aspectoEstablecimiento = aspectoEstablecimiento;
		this.atencionCliente = atencionCliente;
		this.eficienciaServicio = eficienciaServicio;
		this.higieneEstablecimiento = higieneEstablecimiento;
		this.relacionPrecioCalidad = relacionPrecioCalidad;
		this.accesibilidad = accesibilidad;
		this.comunicacion = comunicacion;
		this.manejoIdiomas = manejoIdiomas;
		this.senalamientoInterno = senalamientoInterno;
		this.senalamientoExterno = senalamientoExterno;
	}

	public Evaluacionservicioturistico(String comentario, int TIdUsuario, int teIdEvaluacion,
			int aspectoEstablecimiento, int atencionCliente, int eficienciaServicio, int higieneEstablecimiento,
			int relacionPrecioCalidad, int accesibilidad, int comunicacion, int manejoIdiomas, int senalamientoInterno,
			int senalamientoExterno) {
		this.comentario = comentario;
		this.TIdUsuario = TIdUsuario;
		this.teIdEvaluacion = teIdEvaluacion;
		this.aspectoEstablecimiento = aspectoEstablecimiento;
		this.atencionCliente = atencionCliente;
		this.eficienciaServicio = eficienciaServicio;
		this.higieneEstablecimiento = higieneEstablecimiento;
		this.relacionPrecioCalidad = relacionPrecioCalidad;
		this.accesibilidad = accesibilidad;
		this.comunicacion = comunicacion;
		this.manejoIdiomas = manejoIdiomas;
		this.senalamientoInterno = senalamientoInterno;
		this.senalamientoExterno = senalamientoExterno;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEvaluacion", unique = true, nullable = false)
	public Integer getIdEvaluacion() {
		return this.idEvaluacion;
	}

	public void setIdEvaluacion(Integer idEvaluacion) {
		this.idEvaluacion = idEvaluacion;
	}

	@Column(name = "comentario", length = 65535)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "t_idUsuario", nullable = false)
	public int getTIdUsuario() {
		return this.TIdUsuario;
	}

	public void setTIdUsuario(int TIdUsuario) {
		this.TIdUsuario = TIdUsuario;
	}

	@Column(name = "tE_idEvaluacion", nullable = false)
	public int getTeIdEvaluacion() {
		return this.teIdEvaluacion;
	}

	public void setTeIdEvaluacion(int teIdEvaluacion) {
		this.teIdEvaluacion = teIdEvaluacion;
	}

	@Column(name = "aspectoEstablecimiento", nullable = false)
	public int getAspectoEstablecimiento() {
		return this.aspectoEstablecimiento;
	}

	public void setAspectoEstablecimiento(int aspectoEstablecimiento) {
		this.aspectoEstablecimiento = aspectoEstablecimiento;
	}

	@Column(name = "atencionCliente", nullable = false)
	public int getAtencionCliente() {
		return this.atencionCliente;
	}

	public void setAtencionCliente(int atencionCliente) {
		this.atencionCliente = atencionCliente;
	}

	@Column(name = "eficienciaServicio", nullable = false)
	public int getEficienciaServicio() {
		return this.eficienciaServicio;
	}

	public void setEficienciaServicio(int eficienciaServicio) {
		this.eficienciaServicio = eficienciaServicio;
	}

	@Column(name = "higieneEstablecimiento", nullable = false)
	public int getHigieneEstablecimiento() {
		return this.higieneEstablecimiento;
	}

	public void setHigieneEstablecimiento(int higieneEstablecimiento) {
		this.higieneEstablecimiento = higieneEstablecimiento;
	}

	@Column(name = "relacionPrecioCalidad", nullable = false)
	public int getRelacionPrecioCalidad() {
		return this.relacionPrecioCalidad;
	}

	public void setRelacionPrecioCalidad(int relacionPrecioCalidad) {
		this.relacionPrecioCalidad = relacionPrecioCalidad;
	}

	@Column(name = "accesibilidad", nullable = false)
	public int getAccesibilidad() {
		return this.accesibilidad;
	}

	public void setAccesibilidad(int accesibilidad) {
		this.accesibilidad = accesibilidad;
	}

	@Column(name = "comunicacion", nullable = false)
	public int getComunicacion() {
		return this.comunicacion;
	}

	public void setComunicacion(int comunicacion) {
		this.comunicacion = comunicacion;
	}

	@Column(name = "manejoIdiomas", nullable = false)
	public int getManejoIdiomas() {
		return this.manejoIdiomas;
	}

	public void setManejoIdiomas(int manejoIdiomas) {
		this.manejoIdiomas = manejoIdiomas;
	}

	@Column(name = "senalamientoInterno", nullable = false)
	public int getSenalamientoInterno() {
		return this.senalamientoInterno;
	}

	public void setSenalamientoInterno(int senalamientoInterno) {
		this.senalamientoInterno = senalamientoInterno;
	}

	@Column(name = "senalamientoExterno", nullable = false)
	public int getSenalamientoExterno() {
		return this.senalamientoExterno;
	}

	public void setSenalamientoExterno(int senalamientoExterno) {
		this.senalamientoExterno = senalamientoExterno;
	}

}
