package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Evaluacionaventura generated by hbm2java
 */
@Entity
@Table(name = "evaluacionaventura", catalog = "pueblosMagicos")
public class Evaluacionaventura implements java.io.Serializable
{

	private int EIdevaluacion;
	private Integer senalizacionInstalaciones;
	private Integer equipamientoYMaterial;
	private Integer informacionActividad;
	private Integer informacionRiesgos;
	private Integer condicionEquipo;
	private Integer informacionRequisitos;
	private Integer servicioMedico;
	private Integer seguroVida;
	private Integer acuerdoRiesgos;
	private Integer supervision;
	private Integer asistencia;
	private Integer informacionReservaLugar;

	public Evaluacionaventura()
	{
	}

	public Evaluacionaventura(int EIdevaluacion)
	{
		this.EIdevaluacion = EIdevaluacion;
	}

	public Evaluacionaventura(int EIdevaluacion, Integer senalizacionInstalaciones, Integer equipamientoYMaterial,
			Integer informacionActividad, Integer informacionRiesgos, Integer condicionEquipo,
			Integer informacionRequisitos, Integer servicioMedico, Integer seguroVida, Integer acuerdoRiesgos,
			Integer supervision, Integer asistencia, Integer informacionReservaLugar)
	{
		this.EIdevaluacion = EIdevaluacion;
		this.senalizacionInstalaciones = senalizacionInstalaciones;
		this.equipamientoYMaterial = equipamientoYMaterial;
		this.informacionActividad = informacionActividad;
		this.informacionRiesgos = informacionRiesgos;
		this.condicionEquipo = condicionEquipo;
		this.informacionRequisitos = informacionRequisitos;
		this.servicioMedico = servicioMedico;
		this.seguroVida = seguroVida;
		this.acuerdoRiesgos = acuerdoRiesgos;
		this.supervision = supervision;
		this.asistencia = asistencia;
		this.informacionReservaLugar = informacionReservaLugar;
	}

	@Id

	@Column(name = "e_idevaluacion", unique = true, nullable = false)
	public int getEIdevaluacion( )
	{
		return this.EIdevaluacion;
	}

	public void setEIdevaluacion( int EIdevaluacion )
	{
		this.EIdevaluacion = EIdevaluacion;
	}

	@Column(name = "senalizacionInstalaciones")
	public Integer getSenalizacionInstalaciones( )
	{
		return this.senalizacionInstalaciones;
	}

	public void setSenalizacionInstalaciones( Integer senalizacionInstalaciones )
	{
		this.senalizacionInstalaciones = senalizacionInstalaciones;
	}

	@Column(name = "equipamiento_y_material")
	public Integer getEquipamientoYMaterial( )
	{
		return this.equipamientoYMaterial;
	}

	public void setEquipamientoYMaterial( Integer equipamientoYMaterial )
	{
		this.equipamientoYMaterial = equipamientoYMaterial;
	}

	@Column(name = "informacionActividad")
	public Integer getInformacionActividad( )
	{
		return this.informacionActividad;
	}

	public void setInformacionActividad( Integer informacionActividad )
	{
		this.informacionActividad = informacionActividad;
	}

	@Column(name = "informacionRiesgos")
	public Integer getInformacionRiesgos( )
	{
		return this.informacionRiesgos;
	}

	public void setInformacionRiesgos( Integer informacionRiesgos )
	{
		this.informacionRiesgos = informacionRiesgos;
	}

	@Column(name = "condicionEquipo")
	public Integer getCondicionEquipo( )
	{
		return this.condicionEquipo;
	}

	public void setCondicionEquipo( Integer condicionEquipo )
	{
		this.condicionEquipo = condicionEquipo;
	}

	@Column(name = "informacionRequisitos")
	public Integer getInformacionRequisitos( )
	{
		return this.informacionRequisitos;
	}

	public void setInformacionRequisitos( Integer informacionRequisitos )
	{
		this.informacionRequisitos = informacionRequisitos;
	}

	@Column(name = "servicioMedico")
	public Integer getServicioMedico( )
	{
		return this.servicioMedico;
	}

	public void setServicioMedico( Integer servicioMedico )
	{
		this.servicioMedico = servicioMedico;
	}

	@Column(name = "seguroVida")
	public Integer getSeguroVida( )
	{
		return this.seguroVida;
	}

	public void setSeguroVida( Integer seguroVida )
	{
		this.seguroVida = seguroVida;
	}

	@Column(name = "acuerdoRiesgos")
	public Integer getAcuerdoRiesgos( )
	{
		return this.acuerdoRiesgos;
	}

	public void setAcuerdoRiesgos( Integer acuerdoRiesgos )
	{
		this.acuerdoRiesgos = acuerdoRiesgos;
	}

	@Column(name = "supervision")
	public Integer getSupervision( )
	{
		return this.supervision;
	}

	public void setSupervision( Integer supervision )
	{
		this.supervision = supervision;
	}

	@Column(name = "asistencia")
	public Integer getAsistencia( )
	{
		return this.asistencia;
	}

	public void setAsistencia( Integer asistencia )
	{
		this.asistencia = asistencia;
	}

	@Column(name = "informacionReservaLugar")
	public Integer getInformacionReservaLugar( )
	{
		return this.informacionReservaLugar;
	}

	public void setInformacionReservaLugar( Integer informacionReservaLugar )
	{
		this.informacionReservaLugar = informacionReservaLugar;
	}

}
