package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Evaluacionalojamiento generated by hbm2java
 */
@Entity
@Table(name = "evaluacionalojamiento", catalog = "pueblosMagicos")
public class Evaluacionalojamiento implements java.io.Serializable {

	private int EIdevaluacion;
	private int instalacionesRecepcion;
	private int servicioPortero;
	private int servicioMaletero;
	private int registroEntrada;
	private int iluminacionHabitacion;
	private int confortCama;
	private int limpiezaBano;
	private int mobiliario;
	private int equipamientoElectronicos;
	private int servicioLavadoPlanchado;

	public Evaluacionalojamiento() {
	}

	public Evaluacionalojamiento(int EIdevaluacion, int instalacionesRecepcion, int servicioPortero,
			int servicioMaletero, int registroEntrada, int iluminacionHabitacion, int confortCama, int limpiezaBano,
			int mobiliario, int equipamientoElectronicos, int servicioLavadoPlanchado) {
		this.EIdevaluacion = EIdevaluacion;
		this.instalacionesRecepcion = instalacionesRecepcion;
		this.servicioPortero = servicioPortero;
		this.servicioMaletero = servicioMaletero;
		this.registroEntrada = registroEntrada;
		this.iluminacionHabitacion = iluminacionHabitacion;
		this.confortCama = confortCama;
		this.limpiezaBano = limpiezaBano;
		this.mobiliario = mobiliario;
		this.equipamientoElectronicos = equipamientoElectronicos;
		this.servicioLavadoPlanchado = servicioLavadoPlanchado;
	}

	@Id

	@Column(name = "e_idevaluacion", unique = true, nullable = false)
	public int getEIdevaluacion() {
		return this.EIdevaluacion;
	}

	public void setEIdevaluacion(int EIdevaluacion) {
		this.EIdevaluacion = EIdevaluacion;
	}

	@Column(name = "instalacionesRecepcion", nullable = false)
	public int getInstalacionesRecepcion() {
		return this.instalacionesRecepcion;
	}

	public void setInstalacionesRecepcion(int instalacionesRecepcion) {
		this.instalacionesRecepcion = instalacionesRecepcion;
	}

	@Column(name = "servicioPortero", nullable = false)
	public int getServicioPortero() {
		return this.servicioPortero;
	}

	public void setServicioPortero(int servicioPortero) {
		this.servicioPortero = servicioPortero;
	}

	@Column(name = "servicioMaletero", nullable = false)
	public int getServicioMaletero() {
		return this.servicioMaletero;
	}

	public void setServicioMaletero(int servicioMaletero) {
		this.servicioMaletero = servicioMaletero;
	}

	@Column(name = "registroEntrada", nullable = false)
	public int getRegistroEntrada() {
		return this.registroEntrada;
	}

	public void setRegistroEntrada(int registroEntrada) {
		this.registroEntrada = registroEntrada;
	}

	@Column(name = "iluminacionHabitacion", nullable = false)
	public int getIluminacionHabitacion() {
		return this.iluminacionHabitacion;
	}

	public void setIluminacionHabitacion(int iluminacionHabitacion) {
		this.iluminacionHabitacion = iluminacionHabitacion;
	}

	@Column(name = "confortCama", nullable = false)
	public int getConfortCama() {
		return this.confortCama;
	}

	public void setConfortCama(int confortCama) {
		this.confortCama = confortCama;
	}

	@Column(name = "limpiezaBano", nullable = false)
	public int getLimpiezaBano() {
		return this.limpiezaBano;
	}

	public void setLimpiezaBano(int limpiezaBano) {
		this.limpiezaBano = limpiezaBano;
	}

	@Column(name = "mobiliario", nullable = false)
	public int getMobiliario() {
		return this.mobiliario;
	}

	public void setMobiliario(int mobiliario) {
		this.mobiliario = mobiliario;
	}

	@Column(name = "equipamientoElectronicos", nullable = false)
	public int getEquipamientoElectronicos() {
		return this.equipamientoElectronicos;
	}

	public void setEquipamientoElectronicos(int equipamientoElectronicos) {
		this.equipamientoElectronicos = equipamientoElectronicos;
	}

	@Column(name = "servicioLavadoPlanchado", nullable = false)
	public int getServicioLavadoPlanchado() {
		return this.servicioLavadoPlanchado;
	}

	public void setServicioLavadoPlanchado(int servicioLavadoPlanchado) {
		this.servicioLavadoPlanchado = servicioLavadoPlanchado;
	}

}
