package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Evaluacionalojamiento generated by hbm2java
 */
@Entity
@Table(name = "evaluacionalojamiento", catalog = "pueblosMagicos")
public class Evaluacionalojamiento implements java.io.Serializable
{

	private int EIdevaluacion;
	private Integer instalacionesRecepcion;
	private Integer servicioPortero;
	private Integer servicioMaletero;
	private Integer registroEntrada;
	private Integer iluminacionHabitacion;
	private Integer confortCama;
	private Integer limpiezaBano;
	private Integer mobiliario;
	private Integer equipamientoElectronicos;
	private Integer servicioLavadoPlanchado;

	public Evaluacionalojamiento()
	{
	}

	public Evaluacionalojamiento(int EIdevaluacion)
	{
		this.EIdevaluacion = EIdevaluacion;
	}

	public Evaluacionalojamiento(int EIdevaluacion, Integer instalacionesRecepcion, Integer servicioPortero,
			Integer servicioMaletero, Integer registroEntrada, Integer iluminacionHabitacion, Integer confortCama,
			Integer limpiezaBano, Integer mobiliario, Integer equipamientoElectronicos, Integer servicioLavadoPlanchado)
	{
		this.EIdevaluacion = EIdevaluacion;
		this.instalacionesRecepcion = instalacionesRecepcion;
		this.servicioPortero = servicioPortero;
		this.servicioMaletero = servicioMaletero;
		this.registroEntrada = registroEntrada;
		this.iluminacionHabitacion = iluminacionHabitacion;
		this.confortCama = confortCama;
		this.limpiezaBano = limpiezaBano;
		this.mobiliario = mobiliario;
		this.equipamientoElectronicos = equipamientoElectronicos;
		this.servicioLavadoPlanchado = servicioLavadoPlanchado;
	}

	@Id

	@Column(name = "e_idevaluacion", unique = true, nullable = false)
	public int getEIdevaluacion( )
	{
		return this.EIdevaluacion;
	}

	public void setEIdevaluacion( int EIdevaluacion )
	{
		this.EIdevaluacion = EIdevaluacion;
	}

	@Column(name = "instalacionesRecepcion")
	public Integer getInstalacionesRecepcion( )
	{
		return this.instalacionesRecepcion;
	}

	public void setInstalacionesRecepcion( Integer instalacionesRecepcion )
	{
		this.instalacionesRecepcion = instalacionesRecepcion;
	}

	@Column(name = "servicioPortero")
	public Integer getServicioPortero( )
	{
		return this.servicioPortero;
	}

	public void setServicioPortero( Integer servicioPortero )
	{
		this.servicioPortero = servicioPortero;
	}

	@Column(name = "servicioMaletero")
	public Integer getServicioMaletero( )
	{
		return this.servicioMaletero;
	}

	public void setServicioMaletero( Integer servicioMaletero )
	{
		this.servicioMaletero = servicioMaletero;
	}

	@Column(name = "registroEntrada")
	public Integer getRegistroEntrada( )
	{
		return this.registroEntrada;
	}

	public void setRegistroEntrada( Integer registroEntrada )
	{
		this.registroEntrada = registroEntrada;
	}

	@Column(name = "iluminacionHabitacion")
	public Integer getIluminacionHabitacion( )
	{
		return this.iluminacionHabitacion;
	}

	public void setIluminacionHabitacion( Integer iluminacionHabitacion )
	{
		this.iluminacionHabitacion = iluminacionHabitacion;
	}

	@Column(name = "confortCama")
	public Integer getConfortCama( )
	{
		return this.confortCama;
	}

	public void setConfortCama( Integer confortCama )
	{
		this.confortCama = confortCama;
	}

	@Column(name = "limpiezaBano")
	public Integer getLimpiezaBano( )
	{
		return this.limpiezaBano;
	}

	public void setLimpiezaBano( Integer limpiezaBano )
	{
		this.limpiezaBano = limpiezaBano;
	}

	@Column(name = "mobiliario")
	public Integer getMobiliario( )
	{
		return this.mobiliario;
	}

	public void setMobiliario( Integer mobiliario )
	{
		this.mobiliario = mobiliario;
	}

	@Column(name = "equipamientoElectronicos")
	public Integer getEquipamientoElectronicos( )
	{
		return this.equipamientoElectronicos;
	}

	public void setEquipamientoElectronicos( Integer equipamientoElectronicos )
	{
		this.equipamientoElectronicos = equipamientoElectronicos;
	}

	@Column(name = "servicioLavadoPlanchado")
	public Integer getServicioLavadoPlanchado( )
	{
		return this.servicioLavadoPlanchado;
	}

	public void setServicioLavadoPlanchado( Integer servicioLavadoPlanchado )
	{
		this.servicioLavadoPlanchado = servicioLavadoPlanchado;
	}

}
