package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Formapago generated by hbm2java
 */
@Entity
@Table(name = "formapago", catalog = "pueblosMagicos")
public class Formapago implements java.io.Serializable {

	private Integer idformaPago;
	private String nombre;

	public Formapago() {
	}

	public Formapago(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idformaPago", unique = true, nullable = false)
	public Integer getIdformaPago() {
		return this.idformaPago;
	}

	public void setIdformaPago(Integer idformaPago) {
		this.idformaPago = idformaPago;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
