package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fotoservicioemergencias generated by hbm2java
 */
@Entity
@Table(name = "fotoservicioemergencias", catalog = "pueblosMagicos")
public class Fotoservicioemergencias implements java.io.Serializable
{

	private Integer idfotoServicioEmergencias;
	private String urlfoto;
	private String descripcion;
	private int sdeIdservicioDeEmergencias;

	public Fotoservicioemergencias()
	{
	}

	public Fotoservicioemergencias(int sdeIdservicioDeEmergencias)
	{
		this.sdeIdservicioDeEmergencias = sdeIdservicioDeEmergencias;
	}

	public Fotoservicioemergencias(String urlfoto, String descripcion, int sdeIdservicioDeEmergencias)
	{
		this.urlfoto = urlfoto;
		this.descripcion = descripcion;
		this.sdeIdservicioDeEmergencias = sdeIdservicioDeEmergencias;
	}
	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idfotoServicioEmergencias", unique = true, nullable = false)
	public Integer getIdfotoServicioEmergencias( )
	{
		return this.idfotoServicioEmergencias;
	}

	public void setIdfotoServicioEmergencias( Integer idfotoServicioEmergencias )
	{
		this.idfotoServicioEmergencias = idfotoServicioEmergencias;
	}

	@Column(name = "URLFoto")
	public String getUrlfoto( )
	{
		return this.urlfoto;
	}

	public void setUrlfoto( String urlfoto )
	{
		this.urlfoto = urlfoto;
	}
	
	@Column(name = "descripcion")
	public String getdescripcion( )
	{
		return this.descripcion;
	}

	public void setdescripcion( String descripcion )
	{
		this.descripcion = descripcion;
	}

	@Column(name = "sDE_idservicioDeEmergencias", nullable = false)
	public int getSdeIdservicioDeEmergencias( )
	{
		return this.sdeIdservicioDeEmergencias;
	}

	public void setSdeIdservicioDeEmergencias( int sdeIdservicioDeEmergencias )
	{
		this.sdeIdservicioDeEmergencias = sdeIdservicioDeEmergencias;
	}

}
