package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fotoatractivoturistico generated by hbm2java
 */
@Entity
@Table(name = "fotoatractivoturistico", catalog = "pueblosMagicos")
public class Fotoatractivoturistico implements java.io.Serializable {

	private Integer idfotoAtractivoTuristico;
	private String urlfoto;
	private int atIdAtractivoTuristico;
	private String descripcion;

	public Fotoatractivoturistico() {
	}

	public Fotoatractivoturistico(int atIdAtractivoTuristico) {
		this.atIdAtractivoTuristico = atIdAtractivoTuristico;
	}

	public Fotoatractivoturistico(String urlfoto, int atIdAtractivoTuristico, String descripcion) {
		this.urlfoto = urlfoto;
		this.atIdAtractivoTuristico = atIdAtractivoTuristico;
		this.descripcion = descripcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idfotoAtractivoTuristico", unique = true, nullable = false)
	public Integer getIdfotoAtractivoTuristico() {
		return this.idfotoAtractivoTuristico;
	}

	public void setIdfotoAtractivoTuristico(Integer idfotoAtractivoTuristico) {
		this.idfotoAtractivoTuristico = idfotoAtractivoTuristico;
	}

	@Column(name = "URLFoto")
	public String getUrlfoto() {
		return this.urlfoto;
	}

	public void setUrlfoto(String urlfoto) {
		this.urlfoto = urlfoto;
	}

	@Column(name = "aT_idAtractivoTuristico", nullable = false)
	public int getAtIdAtractivoTuristico() {
		return this.atIdAtractivoTuristico;
	}

	public void setAtIdAtractivoTuristico(int atIdAtractivoTuristico) {
		this.atIdAtractivoTuristico = atIdAtractivoTuristico;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
