package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fotoservicioemergencias generated by hbm2java
 */
@Entity
@Table(name = "fotoservicioemergencias", catalog = "pueblosMagicos")
public class Fotoservicioemergencias implements java.io.Serializable {

	private Integer idfotoServicioEmergencias;
	private String urlfoto;
	private int sdeIdservicioDeEmergencias;

	public Fotoservicioemergencias() {
	}

	public Fotoservicioemergencias(int sdeIdservicioDeEmergencias) {
		this.sdeIdservicioDeEmergencias = sdeIdservicioDeEmergencias;
	}

	public Fotoservicioemergencias(String urlfoto, int sdeIdservicioDeEmergencias) {
		this.urlfoto = urlfoto;
		this.sdeIdservicioDeEmergencias = sdeIdservicioDeEmergencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idfotoServicioEmergencias", unique = true, nullable = false)
	public Integer getIdfotoServicioEmergencias() {
		return this.idfotoServicioEmergencias;
	}

	public void setIdfotoServicioEmergencias(Integer idfotoServicioEmergencias) {
		this.idfotoServicioEmergencias = idfotoServicioEmergencias;
	}

	@Column(name = "URLFoto")
	public String getUrlfoto() {
		return this.urlfoto;
	}

	public void setUrlfoto(String urlfoto) {
		this.urlfoto = urlfoto;
	}

	@Column(name = "sDE_idservicioDeEmergencias", nullable = false)
	public int getSdeIdservicioDeEmergencias() {
		return this.sdeIdservicioDeEmergencias;
	}

	public void setSdeIdservicioDeEmergencias(int sdeIdservicioDeEmergencias) {
		this.sdeIdservicioDeEmergencias = sdeIdservicioDeEmergencias;
	}

}
