package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fotopueblomagico generated by hbm2java
 */
@Entity
@Table(name = "fotopueblomagico", catalog = "pueblosMagicos")
public class Fotopueblomagico implements java.io.Serializable
{

	private Integer idfotoPuebloMagico;
	private String urlfoto;
	private String descripcion;
	private Integer pmIdPuebloMagico;

	public Fotopueblomagico()
	{
	}

	public Fotopueblomagico(Integer pmIdPuebloMagico)
	{
		this.pmIdPuebloMagico = pmIdPuebloMagico;
	}

	public Fotopueblomagico(String urlfoto, String descripcion, Integer pmIdPuebloMagico)
	{
		this.urlfoto = urlfoto;
		this.descripcion = descripcion;
		this.pmIdPuebloMagico = pmIdPuebloMagico;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idfotoPuebloMagico", unique = true, nullable = false)
	public Integer getIdfotoPuebloMagico( )
	{
		return this.idfotoPuebloMagico;
	}

	public void setIdfotoPuebloMagico( Integer idfotoPuebloMagico )
	{
		this.idfotoPuebloMagico = idfotoPuebloMagico;
	}

	@Column(name = "URLfoto")
	public String getUrlfoto( )
	{
		return this.urlfoto;
	}

	public void setUrlfoto( String urlfoto )
	{
		this.urlfoto = urlfoto;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion( )
	{
		return this.descripcion;
	}

	public void setDescripcion( String descripcion )
	{
		this.descripcion = descripcion;
	}

	@Column(name = "pM_idPuebloMagico", nullable = false)
	public Integer getPmIdPuebloMagico( )
	{
		return this.pmIdPuebloMagico;
	}

	public void setPmIdPuebloMagico( Integer pmIdPuebloMagico )
	{
		this.pmIdPuebloMagico = pmIdPuebloMagico;
	}

}
