package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fotoservicioturistico generated by hbm2java
 */
@Entity
@Table(name = "fotoservicioturistico", catalog = "pueblosMagicos")
public class Fotoservicioturistico implements java.io.Serializable
{

	private Integer idfotoServicioTuristico;
	private String urlfoto;
	private String descripcion;
	private Integer stIdServicio;

	public Fotoservicioturistico()
	{
	}

	public Fotoservicioturistico(int stIdServicio)
	{
		this.stIdServicio = stIdServicio;
	}

	public Fotoservicioturistico(String urlfoto, String descripcion, Integer stIdServicio)
	{
		this.urlfoto = urlfoto;
		this.descripcion = descripcion;
		this.stIdServicio = stIdServicio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idfotoServicioTuristico", unique = true, nullable = false)
	public Integer getIdfotoServicioTuristico( )
	{
		return this.idfotoServicioTuristico;
	}

	public void setIdfotoServicioTuristico( Integer idfotoServicioTuristico )
	{
		this.idfotoServicioTuristico = idfotoServicioTuristico;
	}

	@Column(name = "URLFoto")
	public String getUrlfoto( )
	{
		return this.urlfoto;
	}

	public void setUrlfoto( String urlfoto )
	{
		this.urlfoto = urlfoto;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion( )
	{
		return this.descripcion;
	}

	public void setDescripcion( String descripcion )
	{
		this.descripcion = descripcion;
	}

	@Column(name = "sT_idServicio", nullable = false)
	public Integer getStIdServicio( )
	{
		return this.stIdServicio;
	}

	public void setStIdServicio( Integer stIdServicio )
	{
		this.stIdServicio = stIdServicio;
	}

}
