package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fotoatractivoturistico generated by hbm2java
 */
@Entity
@Table(name = "fotoatractivoturistico", catalog = "pueblosMagicos")
public class Fotoatractivoturistico implements java.io.Serializable
{

	private Integer idfotoAtractivoTuristico;
	private String urlfoto;
	private Integer atIdAtractivoTuristico;
	private String descripcion;

	public Fotoatractivoturistico()
	{
	}

	public Fotoatractivoturistico(Integer atIdAtractivoTuristico)
	{
		this.atIdAtractivoTuristico = atIdAtractivoTuristico;
	}

	public Fotoatractivoturistico(String urlfoto, Integer atIdAtractivoTuristico, String descripcion)
	{
		this.urlfoto = urlfoto;
		this.atIdAtractivoTuristico = atIdAtractivoTuristico;
		this.descripcion = descripcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idfotoAtractivoTuristico", unique = true, nullable = false)
	public Integer getIdfotoAtractivoTuristico( )
	{
		return this.idfotoAtractivoTuristico;
	}

	public void setIdfotoAtractivoTuristico( Integer idfotoAtractivoTuristico )
	{
		this.idfotoAtractivoTuristico = idfotoAtractivoTuristico;
	}

	@Column(name = "URLFoto")
	public String getUrlfoto( )
	{
		return this.urlfoto;
	}

	public void setUrlfoto( String urlfoto )
	{
		this.urlfoto = urlfoto;
	}

	@Column(name = "aT_idAtractivoTuristico", nullable = false)
	public Integer getAtIdAtractivoTuristico( )
	{
		return this.atIdAtractivoTuristico;
	}

	public void setAtIdAtractivoTuristico( Integer atIdAtractivoTuristico )
	{
		this.atIdAtractivoTuristico = atIdAtractivoTuristico;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion( )
	{
		return this.descripcion;
	}

	public void setDescripcion( String descripcion )
	{
		this.descripcion = descripcion;
	}

}
