package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fotopueblomagico generated by hbm2java
 */
@Entity
@Table(name = "fotopueblomagico", catalog = "pueblosMagicos")
public class Fotopueblomagico implements java.io.Serializable {

	private Integer idfotoPuebloMagico;
	private String urlfoto;
	private String descripcion;
	private int pmIdPuebloMagico;

	public Fotopueblomagico() {
	}

	public Fotopueblomagico(int pmIdPuebloMagico) {
		this.pmIdPuebloMagico = pmIdPuebloMagico;
	}

	public Fotopueblomagico(String urlfoto, String descripcion, int pmIdPuebloMagico) {
		this.urlfoto = urlfoto;
		this.descripcion = descripcion;
		this.pmIdPuebloMagico = pmIdPuebloMagico;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idfotoPuebloMagico", unique = true, nullable = false)
	public Integer getIdfotoPuebloMagico() {
		return this.idfotoPuebloMagico;
	}

	public void setIdfotoPuebloMagico(Integer idfotoPuebloMagico) {
		this.idfotoPuebloMagico = idfotoPuebloMagico;
	}

	@Column(name = "URLfoto")
	public String getUrlfoto() {
		return this.urlfoto;
	}

	public void setUrlfoto(String urlfoto) {
		this.urlfoto = urlfoto;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "pM_idPuebloMagico", nullable = false)
	public int getPmIdPuebloMagico() {
		return this.pmIdPuebloMagico;
	}

	public void setPmIdPuebloMagico(int pmIdPuebloMagico) {
		this.pmIdPuebloMagico = pmIdPuebloMagico;
	}

}
