package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ListaHasServicioturisticoId generated by hbm2java
 */
@Embeddable
public class ListaHasServicioturisticoId implements java.io.Serializable
{

	private int servicioTuristicoIdServicio;
	private int turistaIdUsuario;

	public ListaHasServicioturisticoId()
	{
	}

	public ListaHasServicioturisticoId(int servicioTuristicoIdServicio, int turistaIdUsuario)
	{
		this.servicioTuristicoIdServicio = servicioTuristicoIdServicio;
		this.turistaIdUsuario = turistaIdUsuario;
	}

	

	@Column(name = "servicioTuristico_idServicio", nullable = false)
	public int getServicioTuristicoIdServicio( )
	{
		return this.servicioTuristicoIdServicio;
	}

	public void setServicioTuristicoIdServicio( int servicioTuristicoIdServicio )
	{
		this.servicioTuristicoIdServicio = servicioTuristicoIdServicio;
	}

	@Column(name = "Turista_idUsuario", nullable = false)
	public int getTuristaIdUsuario( )
	{
		return this.turistaIdUsuario;
	}

	public void setTuristaIdUsuario( int turistaIdUsuario )
	{
		this.turistaIdUsuario = turistaIdUsuario;
	}

	public boolean equals( Object other )
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ListaHasServicioturisticoId))
			return false;
		ListaHasServicioturisticoId castOther = (ListaHasServicioturisticoId) other;

		return (this.getServicioTuristicoIdServicio() == castOther.getServicioTuristicoIdServicio())
				&& (this.getTuristaIdUsuario() == castOther.getTuristaIdUsuario());
	}

	public int hashCode( )
	{
		int result = 17;

		result = 37 * result + this.getServicioTuristicoIdServicio();
		result = 37 * result + this.getTuristaIdUsuario();
		return result;
	}

}
