package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MunicipioId generated by hbm2java
 */
@Embeddable
public class MunicipioId implements java.io.Serializable {

	private int idMunicipio;
	private int EIdEstado;

	public MunicipioId() {
	}

	public MunicipioId(int idMunicipio, int EIdEstado) {
		this.idMunicipio = idMunicipio;
		this.EIdEstado = EIdEstado;
	}

	@Column(name = "idMunicipio", nullable = false)
	public int getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(int idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	@Column(name = "e_idEstado", nullable = false)
	public int getEIdEstado() {
		return this.EIdEstado;
	}

	public void setEIdEstado(int EIdEstado) {
		this.EIdEstado = EIdEstado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MunicipioId))
			return false;
		MunicipioId castOther = (MunicipioId) other;

		return (this.getIdMunicipio() == castOther.getIdMunicipio())
				&& (this.getEIdEstado() == castOther.getEIdEstado());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMunicipio();
		result = 37 * result + this.getEIdEstado();
		return result;
	}

}
