package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name = "municipio", catalog = "pueblosMagicos")
public class Municipio implements java.io.Serializable {

	private MunicipioId id;
	private String nombreMunicipio;

	public Municipio() {
	}

	public Municipio(MunicipioId id) {
		this.id = id;
	}

	public Municipio(MunicipioId id, String nombreMunicipio) {
		this.id = id;
		this.nombreMunicipio = nombreMunicipio;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idMunicipio", column = @Column(name = "idMunicipio", nullable = false)),
			@AttributeOverride(name = "EIdEstado", column = @Column(name = "e_idEstado", nullable = false)) })
	public MunicipioId getId() {
		return this.id;
	}

	public void setId(MunicipioId id) {
		this.id = id;
	}

	@Column(name = "nombreMunicipio", length = 60)
	public String getNombreMunicipio() {
		return this.nombreMunicipio;
	}

	public void setNombreMunicipio(String nombreMunicipio) {
		this.nombreMunicipio = nombreMunicipio;
	}

}
