package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pst generated by hbm2java
 */
@Entity
@Table(name = "pst", catalog = "pueblosMagicos")
public class Pst implements java.io.Serializable
{

	private Integer idUsuario;
	private String numeroRnt;
	private String telefono;
	private String razonSocialEmpresa;
	private Integer VIdUsuario;
	private Integer erIdEstadoRegistro;

	public Pst()
	{
	}

	public Pst(Integer idUsuario, Integer erIdEstadoRegistro)
	{
		this.idUsuario = idUsuario;
		this.erIdEstadoRegistro = erIdEstadoRegistro;
	}

	public Pst(Integer idUsuario, String numeroRnt, String telefono, String razonSocialEmpresa, Integer VIdUsuario,
			Integer erIdEstadoRegistro)
	{
		this.idUsuario = idUsuario;
		this.numeroRnt = numeroRnt;
		this.telefono = telefono;
		this.razonSocialEmpresa = razonSocialEmpresa;
		this.VIdUsuario = VIdUsuario;
		this.erIdEstadoRegistro = erIdEstadoRegistro;
	}

	@Id

	@Column(name = "idUsuario", unique = true, nullable = false)
	public Integer getIdUsuario( )
	{
		return this.idUsuario;
	}

	public void setIdUsuario( Integer idUsuario )
	{
		this.idUsuario = idUsuario;
	}

	@Column(name = "numeroRNT", length = 15)
	public String getNumeroRnt( )
	{
		return this.numeroRnt;
	}

	public void setNumeroRnt( String numeroRnt )
	{
		this.numeroRnt = numeroRnt;
	}

	@Column(name = "telefono", length = 10)
	public String getTelefono( )
	{
		return this.telefono;
	}

	public void setTelefono( String telefono )
	{
		this.telefono = telefono;
	}

	@Column(name = "razonSocialEmpresa", length = 80)
	public String getRazonSocialEmpresa( )
	{
		return this.razonSocialEmpresa;
	}

	public void setRazonSocialEmpresa( String razonSocialEmpresa )
	{
		this.razonSocialEmpresa = razonSocialEmpresa;
	}

	@Column(name = "v_idUsuario")
	public Integer getVIdUsuario( )
	{
		return this.VIdUsuario;
	}

	public void setVIdUsuario( Integer VIdUsuario )
	{
		this.VIdUsuario = VIdUsuario;
	}

	@Column(name = "eR_idEstadoRegistro", nullable = false)
	public Integer getErIdEstadoRegistro( )
	{
		return this.erIdEstadoRegistro;
	}

	public void setErIdEstadoRegistro( Integer erIdEstadoRegistro )
	{
		this.erIdEstadoRegistro = erIdEstadoRegistro;
	}

}
