package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pueblomagico generated by hbm2java
 */
@Entity
@Table(name = "pueblomagico", catalog = "pueblosMagicos")
public class Pueblomagico implements java.io.Serializable {

	private Integer idPuebloMagico;
	private String nombre;
	private double latitud;
	private double longitud;
	private String descripcion;
	private int MIdMunicipio;
	private int MEIdEstado;

	public Pueblomagico() {
	}

	public Pueblomagico(String nombre, double latitud, double longitud, int MIdMunicipio, int MEIdEstado) {
		this.nombre = nombre;
		this.latitud = latitud;
		this.longitud = longitud;
		this.MIdMunicipio = MIdMunicipio;
		this.MEIdEstado = MEIdEstado;
	}

	public Pueblomagico(String nombre, double latitud, double longitud, String descripcion, int MIdMunicipio,
			int MEIdEstado) {
		this.nombre = nombre;
		this.latitud = latitud;
		this.longitud = longitud;
		this.descripcion = descripcion;
		this.MIdMunicipio = MIdMunicipio;
		this.MEIdEstado = MEIdEstado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPuebloMagico", unique = true, nullable = false)
	public Integer getIdPuebloMagico() {
		return this.idPuebloMagico;
	}

	public void setIdPuebloMagico(Integer idPuebloMagico) {
		this.idPuebloMagico = idPuebloMagico;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "latitud", nullable = false, precision = 22, scale = 0)
	public double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", nullable = false, precision = 22, scale = 0)
	public double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(double longitud) {
		this.longitud = longitud;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "m_idMunicipio", nullable = false)
	public int getMIdMunicipio() {
		return this.MIdMunicipio;
	}

	public void setMIdMunicipio(int MIdMunicipio) {
		this.MIdMunicipio = MIdMunicipio;
	}

	@Column(name = "m_e_idEstado", nullable = false)
	public int getMEIdEstado() {
		return this.MEIdEstado;
	}

	public void setMEIdEstado(int MEIdEstado) {
		this.MEIdEstado = MEIdEstado;
	}

}
