package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pueblomagico generated by hbm2java
 */
@Entity
@Table(name = "pueblomagico", catalog = "pueblosMagicos")
public class Pueblomagico implements java.io.Serializable
{

	private Integer idPuebloMagico;
	private String nombre;
	private Double latitud;
	private Double longitud;
	private String descripcion;
	private int MIdMunicipio;
	private Integer epmIdestadoPuebloMagico;

	public Pueblomagico()
	{
	}

	public Pueblomagico(int MIdMunicipio)
	{
		this.MIdMunicipio = MIdMunicipio;
	}

	public Pueblomagico(String nombre, Double latitud, Double longitud, String descripcion, int MIdMunicipio,
			Integer epmIdestadoPuebloMagico)
	{
		this.nombre = nombre;
		this.latitud = latitud;
		this.longitud = longitud;
		this.descripcion = descripcion;
		this.MIdMunicipio = MIdMunicipio;
		this.epmIdestadoPuebloMagico = epmIdestadoPuebloMagico;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPuebloMagico", unique = true, nullable = false)
	public Integer getIdPuebloMagico( )
	{
		return this.idPuebloMagico;
	}

	public void setIdPuebloMagico( Integer idPuebloMagico )
	{
		this.idPuebloMagico = idPuebloMagico;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre( )
	{
		return this.nombre;
	}

	public void setNombre( String nombre )
	{
		this.nombre = nombre;
	}

	@Column(name = "latitud", precision = 22, scale = 0)
	public Double getLatitud( )
	{
		return this.latitud;
	}

	public void setLatitud( Double latitud )
	{
		this.latitud = latitud;
	}

	@Column(name = "longitud", precision = 22, scale = 0)
	public Double getLongitud( )
	{
		return this.longitud;
	}

	public void setLongitud( Double longitud )
	{
		this.longitud = longitud;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion( )
	{
		return this.descripcion;
	}

	public void setDescripcion( String descripcion )
	{
		this.descripcion = descripcion;
	}

	@Column(name = "m_idMunicipio", nullable = false)
	public int getMIdMunicipio( )
	{
		return this.MIdMunicipio;
	}

	public void setMIdMunicipio( int MIdMunicipio )
	{
		this.MIdMunicipio = MIdMunicipio;
	}

	
	@Column(name = "ePM_idestadoPuebloMagico")
	public Integer getEpmIdestadoPuebloMagico( )
	{
		return this.epmIdestadoPuebloMagico;
	}

	public void setEpmIdestadoPuebloMagico( Integer epmIdestadoPuebloMagico )
	{
		this.epmIdestadoPuebloMagico = epmIdestadoPuebloMagico;
	}

}
