package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servicioturisticorestauracion generated by hbm2java
 */
@Entity
@Table(name = "servicioturisticorestauracion", catalog = "pueblosMagicos")
public class Servicioturisticorestauracion implements java.io.Serializable
{

	private Integer stIdServicioTuristico;
	private Integer tsrIdtipoServicioRestauracion;

	public Servicioturisticorestauracion()
	{
	}

	public Servicioturisticorestauracion(Integer stIdServicioTuristico, Integer tsrIdtipoServicioRestauracion)
	{
		this.stIdServicioTuristico = stIdServicioTuristico;
		this.tsrIdtipoServicioRestauracion = tsrIdtipoServicioRestauracion;
	}

	@Id

	@Column(name = "sT_idServicioTuristico", unique = true, nullable = false)
	public Integer getStIdServicioTuristico( )
	{
		return this.stIdServicioTuristico;
	}

	public void setStIdServicioTuristico( Integer stIdServicioTuristico )
	{
		this.stIdServicioTuristico = stIdServicioTuristico;
	}

	@Column(name = "tSR_idtipoServicioRestauracion", nullable = false)
	public Integer getTsrIdtipoServicioRestauracion( )
	{
		return this.tsrIdtipoServicioRestauracion;
	}

	public void setTsrIdtipoServicioRestauracion( Integer tsrIdtipoServicioRestauracion )
	{
		this.tsrIdtipoServicioRestauracion = tsrIdtipoServicioRestauracion;
	}

}
