package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servicioturisticoalojamiento generated by hbm2java
 */
@Entity
@Table(name = "servicioturisticoalojamiento", catalog = "pueblosMagicos")
public class Servicioturisticoalojamiento implements java.io.Serializable
{

	private int stIdServicio;
	private int toIdtipoOperacion;
	private int taIdtipoAlojamiento;
	private int tsaIdtipoServicioAlojamiento;

	public Servicioturisticoalojamiento()
	{
	}

	public Servicioturisticoalojamiento(int stIdServicio, int toIdtipoOperacion, int taIdtipoAlojamiento,
			int tsaIdtipoServicioAlojamiento)
	{
		this.stIdServicio = stIdServicio;
		this.toIdtipoOperacion = toIdtipoOperacion;
		this.taIdtipoAlojamiento = taIdtipoAlojamiento;
		this.tsaIdtipoServicioAlojamiento = tsaIdtipoServicioAlojamiento;
	}

	@Id

	@Column(name = "sT_idServicio", unique = true, nullable = false)
	public int getStIdServicio( )
	{
		return this.stIdServicio;
	}

	public void setStIdServicio( int stIdServicio )
	{
		this.stIdServicio = stIdServicio;
	}

	@Column(name = "tO_idtipoOperacion", nullable = false)
	public int getToIdtipoOperacion( )
	{
		return this.toIdtipoOperacion;
	}

	public void setToIdtipoOperacion( int toIdtipoOperacion )
	{
		this.toIdtipoOperacion = toIdtipoOperacion;
	}

	@Column(name = "tA_idtipoAlojamiento", nullable = false)
	public int getTaIdtipoAlojamiento( )
	{
		return this.taIdtipoAlojamiento;
	}

	public void setTaIdtipoAlojamiento( int taIdtipoAlojamiento )
	{
		this.taIdtipoAlojamiento = taIdtipoAlojamiento;
	}

	@Column(name = "tSA_idtipoServicioAlojamiento", nullable = false)
	public int getTsaIdtipoServicioAlojamiento( )
	{
		return this.tsaIdtipoServicioAlojamiento;
	}

	public void setTsaIdtipoServicioAlojamiento( int tsaIdtipoServicioAlojamiento )
	{
		this.tsaIdtipoServicioAlojamiento = tsaIdtipoServicioAlojamiento;
	}

}
