package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servicioturisticoalojamiento generated by hbm2java
 */
@Entity
@Table(name = "servicioturisticoalojamiento", catalog = "pueblosMagicos")
public class Servicioturisticoalojamiento implements java.io.Serializable
{

	private Integer stIdServicio;
	private Integer toIdtipoOperacion;
	private Integer taIdtipoAlojamiento;
	private Integer tsaIdtipoServicioAlojamiento;

	public Servicioturisticoalojamiento()
	{
	}

	public Servicioturisticoalojamiento(Integer stIdServicio, Integer toIdtipoOperacion, Integer taIdtipoAlojamiento,
			Integer tsaIdtipoServicioAlojamiento)
	{
		this.stIdServicio = stIdServicio;
		this.toIdtipoOperacion = toIdtipoOperacion;
		this.taIdtipoAlojamiento = taIdtipoAlojamiento;
		this.tsaIdtipoServicioAlojamiento = tsaIdtipoServicioAlojamiento;
	}

	@Id

	@Column(name = "sT_idServicio", unique = true, nullable = false)
	public Integer getStIdServicio( )
	{
		return this.stIdServicio;
	}

	public void setStIdServicio( Integer stIdServicio )
	{
		this.stIdServicio = stIdServicio;
	}

	@Column(name = "tO_idtipoOperacion", nullable = false)
	public Integer getToIdtipoOperacion( )
	{
		return this.toIdtipoOperacion;
	}

	public void setToIdtipoOperacion( Integer toIdtipoOperacion )
	{
		this.toIdtipoOperacion = toIdtipoOperacion;
	}

	@Column(name = "tA_idtipoAlojamiento", nullable = false)
	public Integer getTaIdtipoAlojamiento( )
	{
		return this.taIdtipoAlojamiento;
	}

	public void setTaIdtipoAlojamiento( Integer taIdtipoAlojamiento )
	{
		this.taIdtipoAlojamiento = taIdtipoAlojamiento;
	}

	@Column(name = "tSA_idtipoServicioAlojamiento", nullable = false)
	public Integer getTsaIdtipoServicioAlojamiento( )
	{
		return this.tsaIdtipoServicioAlojamiento;
	}

	public void setTsaIdtipoServicioAlojamiento( Integer tsaIdtipoServicioAlojamiento )
	{
		this.tsaIdtipoServicioAlojamiento = tsaIdtipoServicioAlojamiento;
	}

}
