package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servicioturistico generated by hbm2java
 */
@Entity
@Table(name = "servicioturistico", catalog = "pueblosMagicos")
public class Servicioturistico implements java.io.Serializable
{

	private Integer idServicioTuristico;
	private Integer EIdEstablecimiento;
	private String nombre;
	private Integer aforo;
	private Integer tstIdtSt;
	private Integer VIdUsuario;
	private Double precioMinimo;
	private Double precioMaximo;
	private Double precioMedio;
	private String descripcion;
	private String sitioWeb;
	private Integer erIdEstadoRegistro;
	private String telefono;
	private String extensionTelefono;
	private Float promedio;

	public Servicioturistico()
	{
	}

	public Servicioturistico(Integer EIdEstablecimiento, Integer tstIdtSt, Integer VIdUsuario, 
			Integer erIdEstadoRegistro)
	{
		this.EIdEstablecimiento = EIdEstablecimiento;
		this.tstIdtSt = tstIdtSt;
		this.VIdUsuario = VIdUsuario;
		this.erIdEstadoRegistro = erIdEstadoRegistro;
	}

	public Servicioturistico(Integer EIdEstablecimiento, String nombre, Integer aforo, Integer tstIdtSt, Integer VIdUsuario,
			Double precioMinimo, Double precioMaximo, Double precioMedio, String descripcion,
			String sitioWeb, Integer erIdEstadoRegistro, String telefono, String extensionTelefono, Float promedio)
	{
		this.EIdEstablecimiento = EIdEstablecimiento;
		this.nombre = nombre;
		this.aforo = aforo;
		this.tstIdtSt = tstIdtSt;
		this.VIdUsuario = VIdUsuario;
		this.precioMinimo = precioMinimo;
		this.precioMaximo = precioMaximo;
		this.precioMedio = precioMedio;
		this.descripcion = descripcion;
		this.sitioWeb = sitioWeb;
		this.erIdEstadoRegistro = erIdEstadoRegistro;
		this.telefono = telefono;
		this.extensionTelefono = extensionTelefono;
		this.promedio = promedio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idServicioTuristico", unique = true, nullable = false)
	public Integer getIdServicioTuristico( )
	{
		return this.idServicioTuristico;
	}

	public void setIdServicioTuristico( Integer idServicioTuristico )
	{
		this.idServicioTuristico = idServicioTuristico;
	}

	@Column(name = "e_idEstablecimiento", nullable = false)
	public Integer getEIdEstablecimiento( )
	{
		return this.EIdEstablecimiento;
	}

	public void setEIdEstablecimiento( Integer EIdEstablecimiento )
	{
		this.EIdEstablecimiento = EIdEstablecimiento;
	}

	@Column(name = "nombre", length = 80)
	public String getNombre( )
	{
		return this.nombre;
	}

	public void setNombre( String nombre )
	{
		this.nombre = nombre;
	}

	@Column(name = "aforo")
	public Integer getAforo( )
	{
		return this.aforo;
	}

	public void setAforo( Integer aforo )
	{
		this.aforo = aforo;
	}

	@Column(name = "tST_idtST", nullable = false)
	public Integer getTstIdtSt( )
	{
		return this.tstIdtSt;
	}

	public void setTstIdtSt( Integer tstIdtSt )
	{
		this.tstIdtSt = tstIdtSt;
	}

	@Column(name = "v_idUsuario")
	public Integer getVIdUsuario( )
	{
		return this.VIdUsuario;
	}

	public void setVIdUsuario( Integer VIdUsuario )
	{
		this.VIdUsuario = VIdUsuario;
	}

	@Column(name = "precioMinimo", precision = 22, scale = 0)
	public Double getPrecioMinimo( )
	{
		return this.precioMinimo;
	}

	public void setPrecioMinimo( Double precioMinimo )
	{
		this.precioMinimo = precioMinimo;
	}

	@Column(name = "precioMaximo", precision = 22, scale = 0)
	public Double getPrecioMaximo( )
	{
		return this.precioMaximo;
	}

	public void setPrecioMaximo( Double precioMaximo )
	{
		this.precioMaximo = precioMaximo;
	}

	@Column(name = "precioMedio", precision = 22, scale = 0)
	public Double getPrecioMedio( )
	{
		return this.precioMedio;
	}

	public void setPrecioMedio( Double precioMedio )
	{
		this.precioMedio = precioMedio;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion( )
	{
		return this.descripcion;
	}

	public void setDescripcion( String descripcion )
	{
		this.descripcion = descripcion;
	}

	@Column(name = "sitioWEB", length = 100)
	public String getSitioWeb( )
	{
		return this.sitioWeb;
	}

	public void setSitioWeb( String sitioWeb )
	{
		this.sitioWeb = sitioWeb;
	}

	@Column(name = "eR_idEstadoRegistro", nullable = false)
	public Integer getErIdEstadoRegistro( )
	{
		return this.erIdEstadoRegistro;
	}

	public void setErIdEstadoRegistro( Integer erIdEstadoRegistro )
	{
		this.erIdEstadoRegistro = erIdEstadoRegistro;
	}
	
	@Column(name = "telefono", length = 15)
	public String getTelefono( )
	{
		return this.telefono;
	}

	public void setTelefono( String telefono )
	{
		this.telefono = telefono;
	}
	
	@Column(name = "extensionTelefono", length = 80)
	public String getExtensionTelefono( )
	{
		return this.extensionTelefono;
	}

	public void setExtensionTelefono( String extensionTelefono )
	{
		this.extensionTelefono = extensionTelefono;
	}

	@Column(name = "promedio")
	public Float getPromedio( )
	{
		return this.promedio;
	}

	public void setPromedio( Float promedio )
	{
		this.promedio = promedio;
	}
}
