package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servicioturisticorestauracion generated by hbm2java
 */
@Entity
@Table(name = "servicioturisticorestauracion", catalog = "pueblosMagicos")
public class Servicioturisticorestauracion implements java.io.Serializable {

	private int stIdServicioTuristico;
	private int tsrIdtipoServicioRestauracion;

	public Servicioturisticorestauracion() {
	}

	public Servicioturisticorestauracion(int stIdServicioTuristico, int tsrIdtipoServicioRestauracion) {
		this.stIdServicioTuristico = stIdServicioTuristico;
		this.tsrIdtipoServicioRestauracion = tsrIdtipoServicioRestauracion;
	}

	@Id

	@Column(name = "sT_idServicioTuristico", unique = true, nullable = false)
	public int getStIdServicioTuristico() {
		return this.stIdServicioTuristico;
	}

	public void setStIdServicioTuristico(int stIdServicioTuristico) {
		this.stIdServicioTuristico = stIdServicioTuristico;
	}

	@Column(name = "tSR_idtipoServicioRestauracion", nullable = false)
	public int getTsrIdtipoServicioRestauracion() {
		return this.tsrIdtipoServicioRestauracion;
	}

	public void setTsrIdtipoServicioRestauracion(int tsrIdtipoServicioRestauracion) {
		this.tsrIdtipoServicioRestauracion = tsrIdtipoServicioRestauracion;
	}

}
