package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servicioturisticoaventura generated by hbm2java
 */
@Entity
@Table(name = "servicioturisticoaventura", catalog = "pueblosMagicos")
public class Servicioturisticoaventura implements java.io.Serializable
{

	private Integer stIdServicio;

	public Servicioturisticoaventura()
	{
	}

	public Servicioturisticoaventura(Integer stIdServicio)
	{
		this.stIdServicio = stIdServicio;
	}

	@Id

	@Column(name = "sT_idServicio", unique = true, nullable = false)
	public Integer getStIdServicio( )
	{
		return this.stIdServicio;
	}

	public void setStIdServicio( Integer stIdServicio )
	{
		this.stIdServicio = stIdServicio;
	}

}
