package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StaHasAsociacion generated by hbm2java
 */
@Entity
@Table(name = "sta_has_asociacion", catalog = "pueblosMagicos")
public class StaHasAsociacion implements java.io.Serializable
{

	private StaHasAsociacionId id;

	public StaHasAsociacion()
	{
	}

	public StaHasAsociacion(StaHasAsociacionId id)
	{
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "staSTIdServicio", column = @Column(name = "sTA_sT_idServicio", nullable = false)),
			@AttributeOverride(name = "AIdasociacion", column = @Column(name = "a_idasociacion", nullable = false)) })
	public StaHasAsociacionId getId( )
	{
		return this.id;
	}

	public void setId( StaHasAsociacionId id )
	{
		this.id = id;
	}

}
