package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StaHasServicioadicionalId generated by hbm2java
 */
@Embeddable
public class StaHasServicioadicionalId implements java.io.Serializable {

	private int staSTIdServicio;
	private int saIdservicioAdicional;

	public StaHasServicioadicionalId() {
	}

	public StaHasServicioadicionalId(int staSTIdServicio, int saIdservicioAdicional) {
		this.staSTIdServicio = staSTIdServicio;
		this.saIdservicioAdicional = saIdservicioAdicional;
	}

	@Column(name = "sTA_sT_idServicio", nullable = false)
	public int getStaSTIdServicio() {
		return this.staSTIdServicio;
	}

	public void setStaSTIdServicio(int staSTIdServicio) {
		this.staSTIdServicio = staSTIdServicio;
	}

	@Column(name = "sA_idservicioAdicional", nullable = false)
	public int getSaIdservicioAdicional() {
		return this.saIdservicioAdicional;
	}

	public void setSaIdservicioAdicional(int saIdservicioAdicional) {
		this.saIdservicioAdicional = saIdservicioAdicional;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StaHasServicioadicionalId))
			return false;
		StaHasServicioadicionalId castOther = (StaHasServicioadicionalId) other;

		return (this.getStaSTIdServicio() == castOther.getStaSTIdServicio())
				&& (this.getSaIdservicioAdicional() == castOther.getSaIdservicioAdicional());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStaSTIdServicio();
		result = 37 * result + this.getSaIdservicioAdicional();
		return result;
	}

}
