package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StaHasTipohabitacion generated by hbm2java
 */
@Entity
@Table(name = "sta_has_tipohabitacion", catalog = "pueblosMagicos")
public class StaHasTipohabitacion implements java.io.Serializable {

	private StaHasTipohabitacionId id;

	public StaHasTipohabitacion() {
	}

	public StaHasTipohabitacion(StaHasTipohabitacionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "staSTIdServicio", column = @Column(name = "sTA_sT_idServicio", nullable = false)),
			@AttributeOverride(name = "thIdtH", column = @Column(name = "tH_idtH", nullable = false)) })
	public StaHasTipohabitacionId getId() {
		return this.id;
	}

	public void setId(StaHasTipohabitacionId id) {
		this.id = id;
	}

}
