package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StaHasAsociacionId generated by hbm2java
 */
@Embeddable
public class StaHasAsociacionId implements java.io.Serializable
{

	private int staSTIdServicio;
	private int AIdasociacion;

	public StaHasAsociacionId()
	{
	}

	public StaHasAsociacionId(int staSTIdServicio, int AIdasociacion)
	{
		this.staSTIdServicio = staSTIdServicio;
		this.AIdasociacion = AIdasociacion;
	}

	@Column(name = "sTA_sT_idServicio", nullable = false)
	public int getStaSTIdServicio( )
	{
		return this.staSTIdServicio;
	}

	public void setStaSTIdServicio( int staSTIdServicio )
	{
		this.staSTIdServicio = staSTIdServicio;
	}

	@Column(name = "a_idasociacion", nullable = false)
	public int getAIdasociacion( )
	{
		return this.AIdasociacion;
	}

	public void setAIdasociacion( int AIdasociacion )
	{
		this.AIdasociacion = AIdasociacion;
	}

	public boolean equals( Object other )
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StaHasAsociacionId))
			return false;
		StaHasAsociacionId castOther = (StaHasAsociacionId) other;

		return (this.getStaSTIdServicio() == castOther.getStaSTIdServicio())
				&& (this.getAIdasociacion() == castOther.getAIdasociacion());
	}

	public int hashCode( )
	{
		int result = 17;

		result = 37 * result + this.getStaSTIdServicio();
		result = 37 * result + this.getAIdasociacion();
		return result;
	}

}
