package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StHasFormapagoId generated by hbm2java
 */
@Embeddable
public class StHasFormapagoId implements java.io.Serializable
{

	private int stIdServicio;
	private int fpIdformaPago;

	public StHasFormapagoId()
	{
	}

	public StHasFormapagoId(int stIdServicio, int fpIdformaPago)
	{
		this.stIdServicio = stIdServicio;
		this.fpIdformaPago = fpIdformaPago;
	}

	@Column(name = "sT_idServicio", nullable = false)
	public int getStIdServicio( )
	{
		return this.stIdServicio;
	}

	public void setStIdServicio( int stIdServicio )
	{
		this.stIdServicio = stIdServicio;
	}

	@Column(name = "fP_idformaPago", nullable = false)
	public int getFpIdformaPago( )
	{
		return this.fpIdformaPago;
	}

	public void setFpIdformaPago( int fpIdformaPago )
	{
		this.fpIdformaPago = fpIdformaPago;
	}

	public boolean equals( Object other )
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StHasFormapagoId))
			return false;
		StHasFormapagoId castOther = (StHasFormapagoId) other;

		return (this.getStIdServicio() == castOther.getStIdServicio())
				&& (this.getFpIdformaPago() == castOther.getFpIdformaPago());
	}

	public int hashCode( )
	{
		int result = 17;

		result = 37 * result + this.getStIdServicio();
		result = 37 * result + this.getFpIdformaPago();
		return result;
	}

}
