package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StHasFormapago generated by hbm2java
 */
@Entity
@Table(name = "st_has_formapago", catalog = "pueblosMagicos")
public class StHasFormapago implements java.io.Serializable {

	private StHasFormapagoId id;

	public StHasFormapago() {
	}

	public StHasFormapago(StHasFormapagoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "stIdServicio", column = @Column(name = "sT_idServicio", nullable = false)),
			@AttributeOverride(name = "fpIdformaPago", column = @Column(name = "fP_idformaPago", nullable = false)) })
	public StHasFormapagoId getId() {
		return this.id;
	}

	public void setId(StHasFormapagoId id) {
		this.id = id;
	}

}
