package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipoalojamiento generated by hbm2java
 */
@Entity
@Table(name = "tipoalojamiento", catalog = "pueblosMagicos")
public class Tipoalojamiento implements java.io.Serializable {

	private int idtipoAlojamiento;
	private String nombre;

	public Tipoalojamiento() {
	}

	public Tipoalojamiento(int idtipoAlojamiento) {
		this.idtipoAlojamiento = idtipoAlojamiento;
	}

	public Tipoalojamiento(int idtipoAlojamiento, String nombre) {
		this.idtipoAlojamiento = idtipoAlojamiento;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idtipoAlojamiento", unique = true, nullable = false)
	public int getIdtipoAlojamiento() {
		return this.idtipoAlojamiento;
	}

	public void setIdtipoAlojamiento(int idtipoAlojamiento) {
		this.idtipoAlojamiento = idtipoAlojamiento;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
