package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tiposervicioturistico generated by hbm2java
 */
@Entity
@Table(name = "tiposervicioturistico", catalog = "pueblosMagicos")
public class Tiposervicioturistico implements java.io.Serializable {

	private Integer idtipoServicioTuristico;
	private String nombre;
	private String descripcion;
	private Integer tstIdtipoServicioTuristico;

	public Tiposervicioturistico() {
	}

	public Tiposervicioturistico(String nombre, String descripcion, Integer tstIdtipoServicioTuristico) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tstIdtipoServicioTuristico = tstIdtipoServicioTuristico;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtipoServicioTuristico", unique = true, nullable = false)
	public Integer getIdtipoServicioTuristico() {
		return this.idtipoServicioTuristico;
	}

	public void setIdtipoServicioTuristico(Integer idtipoServicioTuristico) {
		this.idtipoServicioTuristico = idtipoServicioTuristico;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "tST_idtipoServicioTuristico")
	public Integer getTstIdtipoServicioTuristico() {
		return this.tstIdtipoServicioTuristico;
	}

	public void setTstIdtipoServicioTuristico(Integer tstIdtipoServicioTuristico) {
		this.tstIdtipoServicioTuristico = tstIdtipoServicioTuristico;
	}

}
