package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipoatractivo generated by hbm2java
 */
@Entity
@Table(name = "tipoatractivo", catalog = "pueblosMagicos")
public class Tipoatractivo implements java.io.Serializable {

	private Integer idtipoAtractivo;
	private String nombre;
	private String descripcion;
	private Integer taIdtipoAtractivo;

	public Tipoatractivo() {
	}

	public Tipoatractivo(String nombre, String descripcion, Integer taIdtipoAtractivo) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.taIdtipoAtractivo = taIdtipoAtractivo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtipoAtractivo", unique = true, nullable = false)
	public Integer getIdtipoAtractivo() {
		return this.idtipoAtractivo;
	}

	public void setIdtipoAtractivo(Integer idtipoAtractivo) {
		this.idtipoAtractivo = idtipoAtractivo;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "tA_idtipoAtractivo")
	public Integer getTaIdtipoAtractivo() {
		return this.taIdtipoAtractivo;
	}

	public void setTaIdtipoAtractivo(Integer taIdtipoAtractivo) {
		this.taIdtipoAtractivo = taIdtipoAtractivo;
	}

}
