package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipohabitacion generated by hbm2java
 */
@Entity
@Table(name = "tipohabitacion", catalog = "pueblosMagicos")
public class Tipohabitacion implements java.io.Serializable
{

	private Integer idtipoHabitacion;
	private String nombre;

	public Tipohabitacion()
	{
	}

	public Tipohabitacion(String nombre)
	{
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtipoHabitacion", unique = true, nullable = false)
	public Integer getIdtipoHabitacion( )
	{
		return this.idtipoHabitacion;
	}

	public void setIdtipoHabitacion( Integer idtipoHabitacion )
	{
		this.idtipoHabitacion = idtipoHabitacion;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre( )
	{
		return this.nombre;
	}

	public void setNombre( String nombre )
	{
		this.nombre = nombre;
	}

}
