package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TipoatractivoHasTipoturismoId generated by hbm2java
 */
@Embeddable
public class TipoatractivoHasTipoturismoId implements java.io.Serializable {

	private int taIdtipoAtractivo;
	private int ttIdtipoTurismo;

	public TipoatractivoHasTipoturismoId() {
	}

	public TipoatractivoHasTipoturismoId(int taIdtipoAtractivo, int ttIdtipoTurismo) {
		this.taIdtipoAtractivo = taIdtipoAtractivo;
		this.ttIdtipoTurismo = ttIdtipoTurismo;
	}

	@Column(name = "tA_idtipoAtractivo", nullable = false)
	public int getTaIdtipoAtractivo() {
		return this.taIdtipoAtractivo;
	}

	public void setTaIdtipoAtractivo(int taIdtipoAtractivo) {
		this.taIdtipoAtractivo = taIdtipoAtractivo;
	}

	@Column(name = "tT_idtipoTurismo", nullable = false)
	public int getTtIdtipoTurismo() {
		return this.ttIdtipoTurismo;
	}

	public void setTtIdtipoTurismo(int ttIdtipoTurismo) {
		this.ttIdtipoTurismo = ttIdtipoTurismo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipoatractivoHasTipoturismoId))
			return false;
		TipoatractivoHasTipoturismoId castOther = (TipoatractivoHasTipoturismoId) other;

		return (this.getTaIdtipoAtractivo() == castOther.getTaIdtipoAtractivo())
				&& (this.getTtIdtipoTurismo() == castOther.getTtIdtipoTurismo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTaIdtipoAtractivo();
		result = 37 * result + this.getTtIdtipoTurismo();
		return result;
	}

}
