package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipovialidad generated by hbm2java
 */
@Entity
@Table(name = "tipovialidad", catalog = "pueblosMagicos")
public class Tipovialidad implements java.io.Serializable {

	private Integer idTipoVialidad;
	private String nombre;

	public Tipovialidad() {
	}

	public Tipovialidad(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoVialidad", unique = true, nullable = false)
	public Integer getIdTipoVialidad() {
		return this.idTipoVialidad;
	}

	public void setIdTipoVialidad(Integer idTipoVialidad) {
		this.idTipoVialidad = idTipoVialidad;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
