package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tiposerviciorestauracion generated by hbm2java
 */
@Entity
@Table(name = "tiposerviciorestauracion", catalog = "pueblosMagicos")
public class Tiposerviciorestauracion implements java.io.Serializable {

	private Integer idTipoServicioRestauracion;
	private String nombre;

	public Tiposerviciorestauracion() {
	}

	public Tiposerviciorestauracion(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoServicioRestauracion", unique = true, nullable = false)
	public Integer getIdTipoServicioRestauracion() {
		return this.idTipoServicioRestauracion;
	}

	public void setIdTipoServicioRestauracion(Integer idTipoServicioRestauracion) {
		this.idTipoServicioRestauracion = idTipoServicioRestauracion;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
