package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipooperacionalojamiento generated by hbm2java
 */
@Entity
@Table(name = "tipooperacionalojamiento", catalog = "pueblosMagicos")
public class Tipooperacionalojamiento implements java.io.Serializable
{

	private Integer idTipoOperacionAlojamiento;
	private String nombre;

	public Tipooperacionalojamiento()
	{
	}

	public Tipooperacionalojamiento(String nombre)
	{
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoOperacionAlojamiento", unique = true, nullable = false)
	public Integer getIdTipoOperacionAlojamiento( )
	{
		return this.idTipoOperacionAlojamiento;
	}

	public void setIdTipoOperacionAlojamiento( Integer idTipoOperacionAlojamiento )
	{
		this.idTipoOperacionAlojamiento = idTipoOperacionAlojamiento;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre( )
	{
		return this.nombre;
	}

	public void setNombre( String nombre )
	{
		this.nombre = nombre;
	}

}
