package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TipoatractivoHasTipoturismoId generated by hbm2java
 */
@Embeddable
public class TipoatractivoHasTipoturismoId implements java.io.Serializable
{

	private Integer taIdtipoAtractivo;
	private Integer ttIdtipoTurismo;

	public TipoatractivoHasTipoturismoId()
	{
	}

	public TipoatractivoHasTipoturismoId(Integer taIdtipoAtractivo, Integer ttIdtipoTurismo)
	{
		this.taIdtipoAtractivo = taIdtipoAtractivo;
		this.ttIdtipoTurismo = ttIdtipoTurismo;
	}

	@Column(name = "tA_idtipoAtractivo", nullable = false)
	public Integer getTaIdtipoAtractivo( )
	{
		return this.taIdtipoAtractivo;
	}

	public void setTaIdtipoAtractivo( Integer taIdtipoAtractivo )
	{
		this.taIdtipoAtractivo = taIdtipoAtractivo;
	}

	@Column(name = "tT_idtipoTurismo", nullable = false)
	public Integer getTtIdtipoTurismo( )
	{
		return this.ttIdtipoTurismo;
	}

	public void setTtIdtipoTurismo( Integer ttIdtipoTurismo )
	{
		this.ttIdtipoTurismo = ttIdtipoTurismo;
	}

	public boolean equals( Object other )
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipoatractivoHasTipoturismoId))
			return false;
		TipoatractivoHasTipoturismoId castOther = (TipoatractivoHasTipoturismoId) other;

		return (this.getTaIdtipoAtractivo() == castOther.getTaIdtipoAtractivo())
				&& (this.getTtIdtipoTurismo() == castOther.getTtIdtipoTurismo());
	}

	public int hashCode( )
	{
		int result = 17;

		result = 37 * result + this.getTaIdtipoAtractivo();
		result = 37 * result + this.getTtIdtipoTurismo();
		return result;
	}

}
