package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TipoturismoHasTiposervicioturisticoId generated by hbm2java
 */
@Embeddable
public class TipoturismoHasTiposervicioturisticoId implements java.io.Serializable {

	private int stIdtipoTurismo;
	private int tstIdtipoServicioTuristico;

	public TipoturismoHasTiposervicioturisticoId() {
	}

	public TipoturismoHasTiposervicioturisticoId(int stIdtipoTurismo, int tstIdtipoServicioTuristico) {
		this.stIdtipoTurismo = stIdtipoTurismo;
		this.tstIdtipoServicioTuristico = tstIdtipoServicioTuristico;
	}

	@Column(name = "sT_idtipoTurismo", nullable = false)
	public int getStIdtipoTurismo() {
		return this.stIdtipoTurismo;
	}

	public void setStIdtipoTurismo(int stIdtipoTurismo) {
		this.stIdtipoTurismo = stIdtipoTurismo;
	}

	@Column(name = "tST_idtipoServicioTuristico", nullable = false)
	public int getTstIdtipoServicioTuristico() {
		return this.tstIdtipoServicioTuristico;
	}

	public void setTstIdtipoServicioTuristico(int tstIdtipoServicioTuristico) {
		this.tstIdtipoServicioTuristico = tstIdtipoServicioTuristico;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipoturismoHasTiposervicioturisticoId))
			return false;
		TipoturismoHasTiposervicioturisticoId castOther = (TipoturismoHasTiposervicioturisticoId) other;

		return (this.getStIdtipoTurismo() == castOther.getStIdtipoTurismo())
				&& (this.getTstIdtipoServicioTuristico() == castOther.getTstIdtipoServicioTuristico());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStIdtipoTurismo();
		result = 37 * result + this.getTstIdtipoServicioTuristico();
		return result;
	}

}
