package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Turista generated by hbm2java
 */
@Entity
@Table(name = "turista", catalog = "pueblosMagicos")
public class Turista implements java.io.Serializable
{

	private Integer idUsuario;
	private Date fechaNacimiento;
	private Integer GIdgenero;

	public Turista()
	{
	}

	public Turista(Integer idUsuario, Integer GIdgenero)
	{
		this.idUsuario = idUsuario;
		this.GIdgenero = GIdgenero;
	}

	public Turista(Integer idUsuario, Date fechaNacimiento, Integer GIdgenero)
	{
		this.idUsuario = idUsuario;
		this.fechaNacimiento = fechaNacimiento;
		this.GIdgenero = GIdgenero;
	}

	@Id

	@Column(name = "idUsuario", unique = true, nullable = false)
	public Integer getIdUsuario( )
	{
		return this.idUsuario;
	}

	public void setIdUsuario( Integer idUsuario )
	{
		this.idUsuario = idUsuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaNacimiento", length = 0)
	public Date getFechaNacimiento( )
	{
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento( Date fechaNacimiento )
	{
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "g_idgenero", nullable = false)
	public Integer getGIdgenero( )
	{
		return this.GIdgenero;
	}

	public void setGIdgenero( Integer GIdgenero )
	{
		this.GIdgenero = GIdgenero;
	}

}
