package dto;
// Generated 29/09/2016 02:45:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Validador generated by hbm2java
 */
@Entity
@Table(name = "validador", catalog = "pueblosMagicos")
public class Validador implements java.io.Serializable
{

	private int idUsuario;

	public Validador()
	{
	}

	public Validador(int idUsuario)
	{
		this.idUsuario = idUsuario;
	}

	@Id

	@Column(name = "idUsuario", unique = true, nullable = false)
	public int getIdUsuario( )
	{
		return this.idUsuario;
	}

	public void setIdUsuario( int idUsuario )
	{
		this.idUsuario = idUsuario;
	}

}
