package dto;
// Generated 30/08/2016 02:54:23 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Validador generated by hbm2java
 */
@Entity
@Table(name = "validador", catalog = "pueblosMagicos")
public class Validador implements java.io.Serializable {

	private int idUsuario;

	public Validador() {
	}

	public Validador(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Id

	@Column(name = "idUsuario", unique = true, nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

}
